### ISSUE TITLE
R Tabular Data package library

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#102]
Create an R library for importing (and exporting) tabular data packages.

**UPDATE: Feb 2016 we are collaborting with [rOpenSci](http://ropensci.org/) to produce a feature complete, authoritative R Tabular Data Package Library**

## Work so far

See import work in #23

**Comment by scls19fr** [comment]
+1 for a R Tabular Data package library

**Comment by danfowler** [comment]
rOpenSci Tabular Data Package library: https://github.com/ropenscilabs/datapackage

**Comment by scls19fr** [comment]
It should be add in http://data.okfn.org/tools

Moreover [Contributions Welcome - Update this page](http://github.com/okfn/data.okfn.org/blob/master/views/tools/index.html) is a broken link

**Comment by danfowler** [comment]
Moved: https://trello.com/c/CQV5Dk90/16-as-a-researcher-i-want-to-get-a-data-package-into-r-in-seconds-so-that-i-can-start-using-the-data-for-doing-analysis-and-visuali
