### ISSUE TITLE
OpenRefine Integration

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#103]
Tabular Data Package support in OpenRefine.

Suggest initial focus on export support (import can come later).

**Comment by roll** [comment]
@vitorbaptista Could you please remember what's status of it?

**Comment by vitorbaptista** [comment]
As far as I remember, we started analyzing how to do it, but then decided to prioritize other integrations. Didn't spend much time here.

**Comment by roll** [comment]
Thanks!

**Comment by danfowler** [comment]
Closed in favor of: https://trello.com/c/TmTp3m1r/86-as-a-publisher-working-with-data-packages-i-would-like-an-integration-with-openrefine-so-that-i-can-output-cleaned-data-packages
