### ISSUE TITLE
[super] CKAN + Tabular Data Packages (Import and Export)

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#126]
Push (Tabular) Data Packages to CKAN and their data to CKAN DataStore, and get Data Packages from CKAN.

**Note: heavily updated May 2016**.

Pushing data packages to CKAN and, specifically, data to the DataStore will mean Data Packages can quickly get a nice Data API via the [DataStore API](http://docs.ckan.org/en/latest/maintaining/datastore.html)

* [ ] Import Tabular Data Packages to CKAN #237
* [ ] Export Tabular Data Packages from CKAN (download CKAN datasets onto disk as a Tabular Data Package) #236 

Extras

* [ ] Push "data" to CKAN - not yet data packaged ... (modelled)

### Import - #126

Worth emphasizing overlap with #238 (github => ckan) in terms of the import hook / import step.

<img src="https://docs.google.com/drawings/d/1XqovADufTR5OYRZW0WjeltcYVyCPZ6OVHyfjLSvuJKg/pub?w=1118&h=328" />

Source: https://docs.google.com/drawings/d/1XqovADufTR5OYRZW0WjeltcYVyCPZ6OVHyfjLSvuJKg/edit

## Existing work

* https://github.com/ckan/datapusher - working, Python based. General CSV import into CKAN "webhook" style. Does type guessing. Does *not* currently support JSON Table Schema.
* https://github.com/ckan/ckanext-datapackager - provides CKAN API to import and export `datapackage.json`. **May 2016: does not yet do JTS generation automatically. `schema` and `schemaType` fields are agreed on CKAN but not yet implemented.**
* https://github.com/frictionlessdata/datapackage-ckan-js - pushes metadata and data to CKAN
 * `dpm ckan` uses this to provides CLI support: http://okfnlabs.org/blog/2014/09/11/data-api-for-data-packages-with-dpm-and-ckan.html
* https://github.com/rgrp/ckan-import - incomplete effort to create webhook for automation of Data Package in github => CKAN

**Comment by rgrp** [comment]
Pushing Data Packages was implemented in dpm last year: http://okfnlabs.org/blog/2014/09/11/data-api-for-data-packages-with-dpm-and-ckan.html

**Comment by rgrp** [comment]
See also https://github.com/rgrp/ckan-import - more of generic import.

**Comment by danfowler** [comment]
Fixed by:
- https://github.com/ckan/ckanext-datapackager/

**Comment by rgrp** [comment]
@danfowler where is the support for data import into the DataStore. Does the ckanext-datapackager do this? I thought it only did metadata. Delighted if it does both but good to clarify.

**Comment by pwalsh** [comment]
@rgrp you are right, it does not push to datastore. @danfowler can you open an issue on the actual repo for datastore support.

**Comment by rgrp** [comment]
@pwalsh I should emphasize my view that such a thing should almost certainly be a separate mini service (that you integrate) rather than built in to CKAN (data import is non-trivial as we know from OpenSpending: it involves guess, model, validate and then ingest). I think it is definitely best developed as a separate app or service.

The current CKAN integration in terms of a simple API support for getting and setting data package json is great. However, integrating much more would probably not be wise -- first get this working as its own standalone html+json style app (at least on model, validate etc) and *then* move to integrate (if you want to integrate at all)

**Comment by danfowler** [comment]
@rgrp @pwalsh I made the issue on the other repo, but we can definitely reopen this one if it makes more sense as a separate service.

**Comment by rgrp** [comment]
Re-opening: clear that we still have some work to do here.

**Comment by rgrp** [comment]
Added notes about existing implmentations and new diagram about CKAN import showing steps involved and overall architecture.

**Comment by danfowler** [comment]
Moved here: https://trello.com/c/68MSc1qF/92-as-a-researcher-publisher-i-want-to-publish-data-packages-to-ckan-and-data-pushed-to-the-datastore-so-that-my-data-is-findable-a
