### ISSUE TITLE
Validate tool supports file upload

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#151]
As a Data Package creator I want to validate my datapackage.json as often and early as possible and usually before I have uploaded it somewhere so that it is correct before I publish it online

**Comment by rgrp** [comment]
@sxren interested in this one?

**Comment by danfowler** [comment]
Closed in favor of: https://trello.com/c/rVyhftXe/87-as-a-data-package-creator-i-want-to-validate-my-datapackage-json-as-often-and-early-as-possible-and-usually-before-i-have-upload
