### ISSUE TITLE
Work out if possible to publish data packages online in Google Drive and Dropbox

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#153]
Work out if possible to publish data packages online in:

* Google Drive
* Dropbox

Then update: http://data.okfn.org/doc/publish-online

Key issue here is preserving directory paths online.

**Comment by rgrp** [comment]
@sxren would you be up for contributing here? You seem to know some stuff about dropbox based on https://github.com/datasets/registry/issues/71#issuecomment-74424888

**Comment by sxren** [comment]
@rgrp ok.

i submitted a PR for google drive.

i haven't used dropbox for myself for a while and i no longer have an account. i think the public folder feature would work, but i don't know. maybe someone with a public folder could check.

**Comment by rgrp** [comment]
@sxren great stuff - i mention dropbox as you were advising @ekoner about it (we could ask her to help check)

**Comment by ekoner** [comment]
@sxren @rgrp I have a link to [uk-sic-2007-condensed[(https://www.dropbox.com/sh/nzs738vlht7xo6w/AADHdtOBhH_8tZQKKys7W17Ja?dl=0) if that helps.

**Comment by sxren** [comment]
@ekoner yes. thank you very much.

**Comment by danfowler** [comment]
The Google Drive issue has been resolved by @sxren.  Thanks!

https://github.com/okfn/data.okfn.org-new/commit/e05ca9743bb113ca954c0ef0947f2eb04583763c#diff-5dd339bd35924a5ebb6684d2b3c36ddf

DropBox covered by [Key Tips](http://frictionlessdata.io/guides/publish/online/#key-tips).  If this isn't enough, we can re-open as new issue.
