### ISSUE TITLE
MS-SQL support - Import

### ISSUE THREAD

**Issue by matt40k** [frictionlessdata/project#164]
Create a SSIS component to import from datapackage.json

**Comment by rgrp** [comment]
@matt40k this is great. Could you explain a bit about what SSIS is? Also are you up for implementing or just suggesting this as an idea?

**Comment by matt40k** [comment]
SQL Server Integration Services (SSIS) was originally designed as tool build a SQL Server data warehouse, its a very user friendly. In nut shell the UI is like Visio how you have standard components that you drag onto the page then connect up only the end result is a package that moves data from A to B. The package can then be execute as a (scheduled) SQL Job. The package is designed in Visual Studio.

I'm happy to try and implement something, however I'm no expert. I'll put together some (hopefully useful) notes.

**Comment by jamiekt** [comment]
FYI An initiative sprang up over the weekend to support Tabular Data Packages in SSIS. background blog post is here: http://sqlblog.com/blogs/jamie_thomson/archive/2015/03/27/tabular-data-packages-and-a-biml-challenge.aspx, code is here: https://github.com/bimlscript/BETDPI
![2015-03-30_08-10-53](https://cloud.githubusercontent.com/assets/854953/6891572/5cc73724-d6b4-11e4-9217-23eede2a36d6.png)

**Comment by rgrp** [comment]
@jamiekt this is fantastic. Do you want to add info about this to http://data.okfn.org/tools

**Comment by jamiekt** [comment]
Hi @rgrp, sure, happy to. Changes made, pull request is here: https://github.com/okfn/data.okfn.org/pull/169

**Comment by jamiekt** [comment]
Hi @rgrp , thx for accepting the pull request. How long might it be until the change appears at http://data.okfn.org/tools?

**Comment by danfowler** [comment]
Moved: https://trello.com/c/L5UwD7mm/93-as-a-researcher-developer-working-with-data-packages-i-would-like-the-ability-import-export-from-ms-sql-so-that-i-can-use-data-p
