### ISSUE TITLE
MS-SQL support - Export

### ISSUE THREAD

**Issue by matt40k** [frictionlessdata/project#165]
Create a SSIS component to generate a datapackage.json and export the data as JSON

**Comment by rgrp** [comment]
@matt40k can we build on the stuff in #164 ?

**Comment by danfowler** [comment]
Moved: https://trello.com/c/L5UwD7mm/93-as-a-researcher-developer-working-with-data-packages-i-would-like-the-ability-import-export-from-ms-sql-so-that-i-can-use-data-p
