### ISSUE TITLE
Python (Tabular) Data Package Library

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#171]
https://github.com/frictionlessdata/datapackage-py

(was: https://github.com/tryggvib/datapackage)

**Comment by danfowler** [comment]
We now have https://github.com/frictionlessdata/datapackage-py

**Comment by rgrp** [comment]
Ditto to comments on #127

**Comment by danfowler** [comment]
Here's the blog post summarizing the integration work done: http://okfnlabs.org/blog/2016/03/11/frictionless-data-transport-in-python.html

**Comment by rgrp** [comment]
Whilst we have the library it is not quite. v1.0. Re-opening this to reflect that.

**Comment by roll** [comment]
@rgrp please remove my assignment. As we've figured out I couldn't take care of this in the `current` milestone.

**Comment by danfowler** [comment]
Moved: https://trello.com/c/F35hk2hT/82-as-a-developer-i-want-to-get-a-data-package-into-python-in-seconds-so-that-i-can-start-using-the-data-for-doing-analysis-and-vis
