### ISSUE TITLE
Projects and communities to contact re Data Package

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#174]
- Open Health Information Exchange Community - https://ohie.org/
- Research Data Alliance
- National stats agencies ...

**Comment by akuckartz** [comment]
I am not sure what this issue is about, but the Linked Data community probably should be involved.

**Comment by rgrp** [comment]
@akuckartz who and what lists should we contact and would you be up for pinging folks and reporting back here?

**Comment by akuckartz** [comment]
@rgrp I am subscribed to several relevant lists and can send mails there. It would be good to have a set of questions to guide evaluators.

**Comment by danfowler** [comment]
Hi @akuckartz which lists are you subscribed to?

**Comment by akuckartz** [comment]
@danfowler Just suggest some text and I will see what I can do.

**Comment by danfowler** [comment]
@akuckartz 

Open Knowledge is seeking piloting and tool-building opportunities to support researchers and civic technologists in addressing real problems encountered when working with data. 

- Are you a researcher looking for better tooling to manage your data?  Can you imagine a future where standard “data packages” (of, say, country codes, GDP, inflation rates) are automatically downloaded into your statistics program?  
- Do you work at or represent an research data organization, like DataCite, DataONE, RDA, or CODATA, and would like to work with us on complementary issues?
- Are you a developer and have an idea for something we can build together?
- Are you a student looking to learn more about data wrangling, managing research data, or open data in general?

If any of the above apply to you, email us at frictionless-team@okfn.org.

**Comment by danfowler** [comment]
I think this can be closed.
