### ISSUE TITLE
Make a "1-2-3" or "Hello World" of how to publish a data package

### ISSUE THREAD

**Issue by bnvk** [frictionlessdata/project#182]
Starting at [this page](http://data.okfn.org/doc/publish) it starts jumping into implementation details (tabular, geospatial...) kind of quickly without offering users a "quick" way to get involved immediately while in the process of understanding what they're doing bigger picture

**Comment by rgrp** [comment]
Great suggestion! Please keep them coming.

**Comment by gsilvapt** [comment]
The documentation for this will be written under https://github.com/okfn/handbook/issues/88

**Comment by rgrp** [comment]
@gsilvapt this documentation will go on http://frictionlessdata.io/ not on the handbook. In general, *no* issues from this repo will go into the handbook (the handbook can reference frictionlessdata.io).

**Comment by gsilvapt** [comment]
@rgrp Okay, I got it then. Should I "unreference" the issues I recently linked? Or should I leave it?

**Comment by rgrp** [comment]
@gsilvapt just leave it.

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#49
