### ISSUE TITLE
[super] Continuous Data Integration workflows around Data Packages

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#198]
For a long time we've discussed "continuous data integration" and doing this with Data Packages. This is a discussion space for these ideas.

## What do we mean by "Continuous Data Integration"?

Continuous Integration with code means automated running of tests (and sometimes deployments) whenever new code is pushed.

For data, this would mean automatically validating (testing) data and metadata on each new contribution and running any deployment tests.

> Automatically validating a Data Package data against its schema on each commit (assuming the data was stored in git)

## Sub parts

* [x] Demo example - https://github.com/frictionlessdata/ex-continuous-data-integration
* [ ] Proper Library - https://github.com/frictionlessdata/ex-continuous-data-integration/issues/2
* [ ] Section in Tutorial - #240 

## Initial Implementation

We could start out piggy-backing on existing code CI services such as Travis: instead of running code test we run data validate tests as a code test.

By hand version
* [x] create a demo repo - probably clone a core data package dataset
* [x] implement a tiny test script in scripts called datatest.py or similar. Use goodtables to test the data
* [x] turn on travis ci and run the test script
 * [x] bonus points for somehow showing pretty output from goodtables

Standardize:

* [ ] make a simple library: goodtables-ci or similar ;-) - https://github.com/frictionlessdata/ex-continuous-data-integration/issues/2

**Comment by rgrp** [comment]
Working here: https://github.com/frictionlessdata/ex-continuous-data-integration

**Comment by rgrp** [comment]
Working pretty well.

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#48
