### ISSUE TITLE
Embeddable data summary via iframe

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#200]
I increasingly want to embed a summary of my tabular data in my README - basically the summary I get in http://data.okfn.org/tools/view but cut down to only table description part (and perhaps a data preview).

Nice idea would be to have a iframe for this which can then embed in the page.

Ultimately something like the way we embed code gists or the like but doing this for data (packages) ...

**Comment by tfmorris** [comment]
e.g. http://data.okfn.org/tools/view?url=http%3A%2F%2Fdata.okfn.org%2Fdata%2Fcore%2Fairport-codes

**Comment by rgrp** [comment]
@tfmorris *exactly* - but pulling out only the bit that actually summarizes the data file (not repeating the general readme stuff)

**Comment by danfowler** [comment]
Moved: https://trello.com/c/3BheSw0o/95-as-a-developer-publisher-i-want-a-tool-to-create-an-embeddable-data-summary-via-iframe-so-that-i-can-embed-data-summaries-across
