### ISSUE TITLE
Tabular Data Package to reconciliation API endpoint

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#204]
App to take a Tabular Data Package and generation an API endpoint that can be used for reconciliation e.g. in OpenRefine.

**Comment by danfowler** [comment]
Moved: https://trello.com/c/GrcqZEGP/96-as-a-researcher-i-want-an-app-that-generates-an-openrefine-reconciliation-api-endpoint-from-a-tabular-data-package-so-that-i-can
