### ISSUE TITLE
[idea] Data catalog X -> Data Package wrapper

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#210]
I've long been thinking about having standardized "converter / wrappers" that take datasets from well known data catalogs (data.gov, data.gov.uk, worldbank etc) and present these datasets as data packages.

Why?

* This would allow all the standard data package tooling to all these existing catalogs
* We could magically "proxy-include" these existing data catalogs into a central registry

I would suggest we start with the world bank as it has such a nice set of open stats.

**Comment by danfowler** [comment]
I like this idea!

Moved here: https://trello.com/c/H5ZZg8ol/97-as-a-researcher-i-want-an-app-that-creates-proxy-data-packages-for-well-known-and-reliable-data-sources-so-that-i-can-load-high-
