### ISSUE TITLE
[idea] Core data package JQuery form autocomplete widgets

### ISSUE THREAD

**Issue by augusto-herrmann** [frictionlessdata/project#212]
A JQuery plugin library that one could use to just apply to a form control and automagically transform it into an autocomplete field for the specified core dataset (say, airport names). On a separate (hidden or not) field, the id for it would be recorded (say, airport codes). So people could easily use the core datasets as live foreign keys in their databases without replicating data locally.

I think this correlates well with the ['frictionless data' principles](http://data.okfn.org/vision).

Example usage of the proposed library using the [Comprehensive country codes](http://data.okfn.org/data/core/country-codes) dataset:

```html
<form action="record-country">
  <label for="country-input">Country name:</label>
  <input type="text" id="country-input" name="country-input" placeholder="Start type the name of a country..." />
  <label for="country-code">ISO 3166 code:</label>
  <input type="text" id="country-code" name="country-code" readonly="readonly" />
</form>
```
The following pseudo-javascript

```javascript
$("#country-input").data_autocomplete({"dataset": "country-codes", "label": "name"}).field("ISO3166-1-Alpha-2", $("#country-code"));
```

should produce the behaviour described above.

**Comment by augusto-herrmann** [comment]
The concept of *core data packages* has some similarities to the UK GDS's idea of *[data registers](https://gds.blog.gov.uk/2016/03/11/getting-from-data-to-registers/)* and the ODI's *[data as infrastructure](http://theodi.org/what-is-data-infrastructure)*.

This idea leverages the core data packages by greatly simplifying integration:
* making using them in input forms as simple and as straightforward as possible;
* consequently, the databases these forms provide input to are automatically linked the core data packages (with [all the benefits that linked registries provides](https://gds.blog.gov.uk/2015/12/16/linking-registers/)).

**Comment by rgrp** [comment]
@augusto-herrmann yes - we've mentioned data packages to GDS folks a few times over the years and big plus one on this general approach of leveraging data packages :-)

**Comment by danfowler** [comment]
@augusto-herrmann This is a cool idea.  Would you like to boot a simple demo?

I've moved this to our new User Stories Trello board where we are tracking these kinds of ideas: https://trello.com/c/vUKDXvUM/99-as-a-developer-i-want-a-jquery-plugin-for-core-data-packages-so-that-i-can-use-it-to-apply-to-a-form-control-that-uses-a-core-da
