### ISSUE TITLE
EPrints support for import/export of Data Packages

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#214]
[EPrints](http://www.eprints.org/uk/index.php/eprints-software/) is open-source software for running research data repositories with a "flexible plugin architecture for developing extensions".  It is used by, among others, the [UK Data Archive](http://www.data-archive.ac.uk/).

From their website:

> As the first professional software platform for building high quality OAI-compliant repositories, EPrints is already established as the easiest and fastest way to set up repositories of open access research literature, scientific data, theses, reports and multimedia. EPrints 3 is a major leap forward in functionality, giving even more control and flexibility to repository managers, depositors, researchers and technical administrators.

**Comment by pwalsh** [comment]
Can we get some stats on how widely this is used, and also some info on how it came across your path?

**Comment by tfmorris** [comment]
http://roar.eprints.org/view/software/
https://www.google.com/search?q=%22is+powered+by+EPrints+3%22

My take - relatively popular, particularly in the UK, but DSpace is 3 times more popular, even according to EPrints registry, which could be biased towards themselves.

**Comment by danfowler** [comment]
Thanks, @tfmorris.

I did, in fact, learn about EPrints from talking with the UK Data Archive. 

And, you're right, DSpace does seem extremely popular.  I will point out that their [registry](http://registry.duraspace.org/registry/dspace?f[0]=field_country%3Aunited%20states&f[1]=field_institution_type%3Aother) seems to be riven with spam.

**Comment by danfowler** [comment]
Moving this User Story to our new User Stories Trello Board: https://trello.com/c/NkJ2jQXI/1-as-a-developer-working-with-data-packages-i-want-an-eprints-integration-so-i-can-integrate-data-packaged-data-with-pipelines-tha
