### ISSUE TITLE
Move all frictionless tools and libraries from /okfn/ org here

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#220]
Steps for each repo:

* Transfer ownership
* Check README and code for any reference to old location

Repos:

* [x] datapackage-render-js
* [x] datapackage-read-js
* [x] datapackage-init-js
* [x] datapackage-validate-js
* [x] datapackage-identifier (also add -js to end)
* [ ] datapackage-from-remote-js - should we merge/deprecate
* [x] datapackage-registry-js
* [ ] datapackage-outfile-js - should we deprecate this?
* [x] datapackage-ckan - and add -js
* [x] datapackage-to-google-spreadsheet (should we move?)
* [x] json-table-schema-infer (and add -js to end)
* [ ] https://github.com/okfn/messytables - should this move?

Archive (to oki-archive):

* [x] datapackage-validate-py (deprecated and replaced by all-in-one datapackage-py)
* [x] datapackage-registry-py (deprecated and replaced by all-in-one datapackage-py)
* [x] datapackage-storage-py (deprecated and replaced by all-in-one datapackage-py)
* [x] datapackage-registry-py (deprecated and replaced by all-in-one datapackage-py)
* [x] datapackage-bigquery-py (deprecated and replaced by all-in-one datapackage-py)
* [x] datapackage-sql-py (deprecated and replaced by all-in-one datapackage-py)
* [x] datapackage.js-deprecated

May also want to do some consolidation e.g.

* [ ] datapackage-remote-js and datapackage-read-js - see https://github.com/okfn/datapackage-from-remote-js/issues/15
* [ ] datapackage-outfile-js - should this just be a gist? See https://github.com/okfn/datapackage-outfile-js/issues/1

**Comment by rgrp** [comment]
@danfowler one for you ;-)

/cc @pwalsh

**Comment by rgrp** [comment]
@pwalsh should messytables be moving over to frictionlessdata or not? And is messytables sort-of deprecated and if so in favour of what?

**Comment by rgrp** [comment]
@pwalsh other question: "json-table-schema" vs "jsontableschema" - i'm assuming latter from use but e.g. https://github.com/frictionlessdata/jsontableschema-js has node package called json-table-schema ...

**Comment by danfowler** [comment]
@rgrp @pwalsh two /okfn/ datapackage* repos remain: https://github.com/okfn/?utf8=%E2%9C%93&query=datapackage

**Comment by pwalsh** [comment]
DONE
