### ISSUE TITLE
Tutorial: Tabular Data Package in Python

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#221]
## Using

- [x] What will you get to do
- [x] Installing prereqs
   - [x] Python
  - [x] datapackage
- [x] Introduce and describe data packages we will use (prob. need good example data packages: stripped-down and don't change)
- [x] Load data package
- [x] Put it in SQL
- [x] Put it in BigQuery
- [x] Put into AWS RedShift

## Validation
- [ ] Metadata validation
- [x] Data validation (using Goodtables)

## Creating & Updating
- [x] create data package
- [x] inferring schema
- [x] publishing (this points out somewhere else)

**Comment by amercader** [comment]
Feedback for the Quick Start in Python guide here: https://github.com/frictionlessdata/frictionlessdata.io/issues/19

**Comment by danfowler** [comment]
Closed by https://github.com/frictionlessdata/frictionlessdata.io/commit/719921f1d1df5cf03e25b2f322a8f3f0a4b874f0

A full guide exists here: http://frictionlessdata.io/guides/using-data-packages-in-python/
