### ISSUE TITLE
[super] Workflow for Creating a Data Package

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#229]
Overview of workflow for creating a Data Package (and associated tools and tutorials)

Rough flowchart:

* Type of data - Tabular / Geo / Any
* Are you using a library or tool or are you doing by hand
  * ? Python / R / ... => 
  * Doing it by hand => ...

**This could start as a simple diagram ...** - would go on `/guides/publish/` page

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#58
