### ISSUE TITLE
Tutorial: Create or Edit a DataPackage.json by hand

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#230]
Supports: "Creating a Data Package" workflow #229

* [ ] Assume you have your data
* [ ] What is JSON
* [ ] Structure of a `datapackage.json` - see the guides, specs etc
* [ ] Tools to support you (online validators, dpm etc)

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#46
