### ISSUE TITLE
Tutorial: Manage and Publish Data Packages with Github or Gitlab or ...

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#233]
* [ ] Git and Github (assume you are familiar)
* [ ] Pushing your data ... 
* [ ] Benefits
  * [ ] Versioning
  * [ ] Diffs
  * [ ] Pull requests
* [ ] Continuous Data Integration
* [ ] Gotchas - github.com/xxx/yyy !=> github.com/xxx/yyy/datapackage.json etc ...

**Comment by danfowler** [comment]
@rgrp: @phette23 wrote a big part of this already in a really excellent article in mid-2015: 

http://acrl.ala.org/techconnect/post/a-forray-into-publishing-open-data-on-github?utm_source=twitterfeed&utm_medium=twitter

Keeping this issue open as we might want to revisit.

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#39
