### ISSUE TITLE
Improve Developer Guide - how to contribute to tools and specs

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#234]
* [ ] Tools
 * [x] General architecture - what components are there to a full "Data Package" stack
 * [x] Pointers to specific languages e.g. Python, R, ...
 * [x] How to start on a platform integration (what type of platform: publishing, consuming etc)
* [ ] Specs
 * [x] Where to find the main specs
 * [ ] Where to raise issues
* [ ] Test suite

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#45
