### ISSUE TITLE
Github Data Package => CKAN Automated

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#238]
As a Data Wrangler I want to store my Data Package in github and have it automatically pushed into CKAN (or somewhere else) so that I get a nice data API and my dataset is listed in a relevant catalog

Whilst this focuses on CKAN (and Github) it can be a template for more other automated transfer of data.

WIP and further user stories at: https://github.com/rgrp/ckan-import

## Overview Diagram

<img src="https://docs.google.com/drawings/d/1ZTFbvaLW00DGLolOx90eN-h2QGBDA6j9bLfHXPuFXiM/pub?w=797&h=669" />

**Comment by danfowler** [comment]
Moved: https://trello.com/c/qfN4gpG0/81-as-a-developer-data-wrangler-i-want-to-store-my-data-package-in-github-and-have-it-automatically-pushed-into-ckan-so-that-i-get-
