### ISSUE TITLE
Frictionless Data Presentations

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#239]
* [x] [Standard General Intro][intro]
* [ ] Technical Intro (Todo)

[intro]: https://docs.google.com/presentation/d/1ioSCKEY1DKk3aktngC6rG9xTInXaQseSMJzzYFuAVBc/edit#slide=id.g344642f18_18

**Comment by pwalsh** [comment]
@danfowler is this still relevant with all the material you've produced in recent months?

**Comment by pwalsh** [comment]
DONE.
