### ISSUE TITLE
Google Spreadsheet Import

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#24]
* [x] Create appscript code
  * import function
  * simple UI to provide item
* [x] Instructions for using this in your spreadsheet
* [ ] Publish a script which uses the library to the gallery so it can be auto-installed - https://developers.google.com/apps-script/publishing_gallery

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/datapackage-to-google-spreadsheet#8

**Comment by rgrp** [comment]
@danfowler the point of this repo was to track high level progress though - to understand the big tasks and when they were complete. Is that now tracked somewhere else?

**Comment by danfowler** [comment]
@rgrp trying to get to the point where this repo tracks high level progress for active, current work.  This particular issue hasn't been touched in more than two years and only refers to one project.  Now that https://github.com/frictionlessdata/datapackage-to-google-spreadsheet has been created and that there is no work currently being done on it, I believe that that repo is the natural home for this issue until we can agree it can be closed.  We can start a new issue on this repo to track high level progress for the next set of work on the Google Sheets integration when it happens.

For other "high level" ideas about the project, with or without their own GitHub repos, we have a User Stories Trello board: https://trello.com/b/MGC4RpTZ/frictionless-data-user-stories

https://github.com/frictionlessdata/project/issues/262

**Comment by mattfullerton** [comment]
@danfowler @rgrp Sounds good to me. I haven't been able to follow frictionlessdata progress recently apart from noticing that an awful lot is happening. In that sense I have no idea any more of what is still needed here and where it fits in. Happy to help though if there is something to progress here. Or rather not here but in the other repo :wink:
