### ISSUE TITLE
Specifications Work May 2016 onwards

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#241]
Holding issue for summarizing specification work:

Current specs work [Current milestone](https://github.com/frictionlessdata/specs/issues?q=is%3Aopen+is%3Aissue+milestone%3ACurrent).

**Comment by danfowler** [comment]
@roll I removed the User Story label, added a "specs" label, and replaced the checklist with a link to the current milestone: https://github.com/frictionlessdata/specs/issues?q=is%3Aopen+is%3Aissue+milestone%3ACurrent

**Comment by roll** [comment]
@danfowler 
Don't you think to introduce milestone like `specs-v1` (describing a goal) like I have for libs? In my opinion this `current` milestones not very descriptive (also not obvious how it related to our current sprint). Just a suggestion you and WG anyway better knows how to organize work.

**Comment by pwalsh** [comment]
All happening on specs repo, not here.
