### ISSUE TITLE
Provide changelogs for major Data Package libraries

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#243]
It's a good practice especially to document new features and breaking changes.

**Comment by rgrp** [comment]
@roll can you clarify what you mean by "packages" do you mean "Data Packages" or code libraries?

**Comment by roll** [comment]
Sorry I was't clear. Updated:

For FD project we have some packages published on PyPi, NPM etc.
A good practice will be to add changelogs to the most important ones.

Do you think is it right place (ideas) to put tech issues like this?

**Comment by rgrp** [comment]
@roll this is definitely the right place for high level, general points like this. I have renamed the issue title to make it clearer.

**Comment by roll** [comment]
thanks

**Comment by pwalsh** [comment]
We are doing this on new libraries, and it is a case-by-case basis type of thing, so I don't think this issue serves anything by sitting here :)

**Comment by roll** [comment]
Title wasn't correct (more like establish an approach) and now it's done
