### ISSUE TITLE
[pm] Sprint 9 May 2016

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#244]
2 week sprint. We approx follow: https://github.com/rgrp/project-management/blob/master/project-delivery.md#the-sprint-process-and-key-concepts

**Comment by danfowler** [comment]
And now this sprint has ended.

![game-of-thrones-jon-snow-my-watch-has-ended](https://cloud.githubusercontent.com/assets/772616/17487483/fe9c4720-5d62-11e6-861d-668589a2d794.jpg)
