### ISSUE TITLE
Tutorial: JSON Table Schema

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#248]
Already have basics here: http://frictionlessdata.io/guides/json-table-schema

May want to add there or have separate mini-tutorials (if that is focused just on what JTS is ...)

Things to add:

* [x] Inferring the schema - tools
* [x] Use for validation
* [ ] Profiles / registry (if we have it)

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#40
