### ISSUE TITLE
Javascript / NodeJS (Tabular) Data Package Library

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#249]
A full-stack JS implementation

JSON Table Schema: https://github.com/frictionlessdata/jsontableschema-js

* [ ] Core
* [ ] Create / Infer
* [ ] Data Stream (via CSV)
* [ ] Read (trivial)
* [ ] Validate (Data)

(Tabular) Data Package: https://github.com/frictionlessdata/datapackage-js

* [ ] Core
* [ ] Create
* [ ] Stream
* [ ] Render

**Comment by danfowler** [comment]
Moved here: https://trello.com/c/o6LYocpY/63-node-library
