### ISSUE TITLE
List of Data Packages for use in development and testing

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#250]
Standard "test-suite" of Data Packages for developers to use in creating reference implementations.

Currently exists at: https://github.com/frictionlessdata/testsuite-py/tree/master/datasets

Split out of #231.

**Comment by rgrp** [comment]
FIXED. https://github.com/frictionlessdata/testsuite-py/tree/master/datasets - might want to factor out into a dedicated repo at some point and submodule in but that is not a priority.

**Comment by rgrp** [comment]
I am reopening as:

* we do not have a test data package that tests *all* data types
* we do not have a test data package that exercises csv dialect

See gitter chat today e.g.

@jeroenooms so one answer for you right is best data package for testing all types is https://github.com/frictionlessdata/testsuite-py/tree/master/datasets/synthetic (though still not quite complete)

@jeroenooms many types here - https://github.com/frictionlessdata/jsontableschema-sql-py/tree/master/data (articles.json/csv) - but it's just a jsontableschema not a datapackage
but if you need some basis for test datapackage it could be usefull

**Comment by pwalsh** [comment]
Closing as this is tracked [here](https://github.com/frictionlessdata/testsuite/issues)
