### ISSUE TITLE
Data Package Specifications Intro v2

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#255]
Specifications page is now http://frictionlessdata.io/data-packages/

We need to spec out this page and then implement.

## Thoughts

* Better diagrams - see slides in [recent deck from CSVConf][csvconf]
  * [Tabular Data Package](https://docs.google.com/presentation/d/1RPArEutyKXbej1pn3wcqCevIxidE1Ced0rCbjqwELio/edit#slide=id.g12f89ceb45_0_16) - [extraction in progress here](https://docs.google.com/drawings/d/1sVRaYipcjkZtu-kU2isDDXp0PKQLPfa4XD0VL_sQlhU/edit)
  * Tooling
  * Extendable metadata
* Summarize principles and advantages
* Link to summary of specs and full specs (already have this)
* Link to FAQs / patterns / tooling / how to use

[csvconf]: https://docs.google.com/presentation/d/1RPArEutyKXbej1pn3wcqCevIxidE1Ced0rCbjqwELio/edit#slide=id.g12f89ceb45_0_16

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#41
