### ISSUE TITLE
[super] Tutorial: CSV + ...

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#256]
* [ ] Validating CSV - maybe covered by #240 
* [ ] A Schema for CSV -> JSON Table Schema
  * [ ] Inferring it automatically
* [ ] Piping CSV between tools ...

**Comment by danfowler** [comment]
@rgrp "A Schema for CSV -> JSON Table Schema + Inferring it automatically" covered here:

http://frictionlessdata.io/guides/creating-tabular-data-packages-in-python/#inferring-a-csv-schema

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#55
