### ISSUE TITLE
 Tutorial: Join two datasets together auto-magically (GDP + Inflation)

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#257]
**User Story:** As an economist, I want to join data in nominal terms (e.g. GDP) with inflation **so that** I can produce real GDP.

(*split from #252*)

**Comment by davbre** [comment]
Have you considered the [csvkit](http://csvkit.readthedocs.io/en/540/index.html) library, specifically its [csvjoin](http://csvkit.readthedocs.io/en/540/scripts/csvjoin.html) command?

**Comment by danfowler** [comment]
Hi @davbre, thanks for this.  This would be an excellent suggestion normally.  In this case, the idea is to take two Data Packages with their associated metadata/schema, do a typical join operation, and output a new Data Package all using the Data Package libraries we have.  This idea, then, does a few jobs: (a) it flexes the Data Package libraries (b) it demonstrates a use case to possibly support by mapping out the challenges necessary in doing it "manually" and (c) it tests out existing Data Packages that have the GDP/inflation numbers.  Does that makes sense?

**Comment by davbre** [comment]
@danfowler - that's fair enough. Thanks for clarifying :+1:

**Comment by danfowler** [comment]
Hi @davbre: here's what I've written up: https://github.com/frictionlessdata/frictionlessdata.io/pull/27/files

**Comment by danfowler** [comment]
From @rgrp:

> - I think this is useful start in showing exactly *what* we would like automated. It seems clear reading this that I want something like:

>  ```
    dp1 = DataPackage('gdp-url')
    dp2 = DataPackage('price-index-url')
    dp3 = DataPackageTools.join(dp1, dp2, ['Country', 'Year'])    
    dp3.save('path')
    ```

@rgrp This guide doesn't only join on fields, it also creates a new field, "Real GDP".  That could also theoretically be automated.  The new Data Package pulls schema information from its source Data Packages, but perhaps it could also update the `sources` field in some standardized way to help with [provenance](https://en.wikipedia.org/wiki/Provenance#Data_provenance).

**Comment by augusto-herrmann** [comment]
The standards for data provenance are on the [PROV](https://www.w3.org/TR/prov-overview/) specification, a W3C Recommendation.

Unfortunately, PROV does not have a standard JSON serialization - those were defined for XML, RDF (PROV-O) and PROV-N notations only. As data packages fields are based on JSON, we could use [PROV-JSON](https://provenance.ecs.soton.ac.uk/prov-json/), a member submission by the University of Southampton.

I think the two sources and the resulting data package would be mapped to [entities](https://provenance.ecs.soton.ac.uk/prov-json/#term-entity), the tool would be an [agent](https://provenance.ecs.soton.ac.uk/prov-json/#term-agent) and the join operation would be an [activity](https://provenance.ecs.soton.ac.uk/prov-json/#term-Activity).

**Comment by akuckartz** [comment]
Unfortunately PROV-JSON is not based on JSON-LD. Maybe a context can be specified, I do not know. In any case PROV-O can be serialized using JSON-LD.

**Comment by rgrp** [comment]
@augusto-herrmann @akuckartz really useful suggestions and thanks for the expert advice here. Recording provenance will definitely become more important as data processing gets more automated -- though for this simple example we may not include it right now.

**Comment by danfowler** [comment]
This issue has been addressed with following commit: https://github.com/frictionlessdata/frictionlessdata.io/commit/cd5cf1df86c9d165f60f985379d090c50e8f5220

On the site here: http://frictionlessdata.io/guides/joining-tabular-data-in-python/

@sirex has a great Pandas-based example here: http://nbviewer.jupyter.org/gist/sirex/8cf10cca9e0ada6bd1bf805ced35e849

@augusto-herrmann @akuckartz to the extent Data Packages could/should support a way to support provenance, perhaps you can leave an issue on the [specs themselves](https://github.com/frictionlessdata/specs/issues)?  I'll note that something similar has already been addressed and ultimately rejected: https://github.com/frictionlessdata/specs/issues/114
