### ISSUE TITLE
Julia tabular data package library

### ISSUE THREAD

**Issue by scls19fr** [frictionlessdata/project#259]
Hello,

Julia is becoming more and more use in data science
maybe you should consider a Julia tabular data package library

A first step could be a library able to download data (and add them to a local cache)

It will help to access for example most R datasets that will be published as DataPackage
see https://github.com/datasets/registry/issues/163

Kind regads

**Comment by scls19fr** [comment]
Pinging some people involved in https://github.com/johnmyleswhite/RDatasets.jl who might be interested by such a project @johnmyleswhite @randyzwitch @garborg

**Comment by randyzwitch** [comment]
Not sure I understand this project...is there a mailing list where I can get a few questions answered?

From just reading the documentation site, it looks like this just requires reading JSON and plain-text files, which Julia can already do.

**Comment by rgrp** [comment]
@randyzwitch chat channel is here:

https://gitter.im/frictionlessdata/chat

Mailing list / forum is: https://discuss.okfn.org/c/frictionless-data

Intro to Data Packages and Frictionless Data here: http://frictionlessdata.io/data-packages/

@randyzwitch yes it does *just* involve reading a JSON file and CSV - aim is super simplicity but enough descriptiveness to have lossless loading of data. Think of this as like software packaging for data ...

**Comment by randyzwitch** [comment]
My apologies for my inarticulate phrasing with the word 'just'; it was not my intent to trivialize your work in any way. I'm certainly a huge proponent of open source/open data in all its forms.

Let me take a look at your links and see how the Python package works. Given the ubiquity of both data formats and existing Julia functionality, it likely wouldn't be a lot of effort to make a Julia package support your project.

**Comment by rgrp** [comment]
@randyzwitch not at all - i took the "just" in a positive way. We have tried hard to make this super-simple so that it is incredibly easy to implement and support - whilst still delivering real value.

It would be *awesome* to get Julia support in and let us know if there is *anything* we can do to help!

**Comment by danfowler** [comment]
Closing and moving here as we are tracking high-level user stories on Trello: https://trello.com/c/JOlZnkoN/98-as-a-researcher-i-want-to-get-a-data-package-into-julia-in-seconds-so-that-i-can-start-using-the-data-for-doing-analysis-and-vis

@randyzwitch @garborg To learn more about the project, you can also check our [several R libraries](http://frictionlessdata.io/tools/#r) that load Data Packages.  The idea is to store and load related data files as a set and associate some essential metadata with those files (e.g. dialect, schema, etc.) to avoid incorrect guessing errors.  @johnmyleswhite actually wrote a thing about the issues with CSV recently (http://www.johnmyleswhite.com/notebook/2016/09/23/no-juice-for-you-csv-format-it-just-makes-you-more-awful/).  We're trying to fix some of those issues.

You can also subscribe to the Frictionless Data newsletter here: http://frictionlessdata.io/get-involved/#newsletter

**Comment by scls19fr** [comment]
I'm just posting this to keep a track...

It seems that a repository have been created at https://github.com/frictionlessdata/datapackage-jl
see https://github.com/frictionlessdata/datapackage-jl/issues/1
