### ISSUE TITLE
LibreOffice / OpenOffice support for Publishing and Consuming Tabular Data Packages

### ISSUE THREAD

**Issue by scls19fr** [frictionlessdata/project#260]
Hello,

Similar to https://github.com/frictionlessdata/ideas/issues/41

A LibreOffice / OpenOffice support will be a nice feature.

Some features could be

- Load a Tabular Data Package from a URL

- Search the primary Data Package registry and then load the selected Data Package

- Support of disconnected mode

Kind regards

Pinging : @paulharris

**Comment by danfowler** [comment]
Moving this User Story to our new User Stories Trello Board: https://trello.com/c/ZYhsjcbP/78-as-a-researcher-i-want-to-get-a-data-package-into-libreoffice-openoffice-in-seconds-so-that-i-can-start-using-the-data-for-doing
