### ISSUE TITLE
Move data.okfn.org/tools/* to frictionlessdata.io

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#261]
Split out from #206 

* [ ] Move data.okfn.org/tools/view to viewer.frictionlessdata.io
  * [ ] implement redirect
* [ ] Move data.okfn.org/tools/validate to validate.frictionlessdata.io
  * [ ] implement redirect
* [ ] Redirect data.okfn.org/tools -> fd.io/tools
* [ ] Redirect data.okfn.org/create -> datapackagist.okfnlabs.org

**Comment by danfowler** [comment]
per @pwalsh datapackagist.okfnlabs.org is best positioned to replace old validator

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#56
