### ISSUE TITLE
Implement testsuite-js

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#264]
# Overview

We have testsuite for Python libraries -  https://github.com/frictionlessdata/testsuite-py - we need the same for other languages (first to javascript).

# Analysis

We should discover possibility of having it at one repository. It could be problematic because of the way how Travis works (one language environment by default). May be it should be `testsuite-js` repository.

**Comment by pwalsh** [comment]
closing in favor of https://github.com/frictionlessdata/testsuite-py/issues/22
