### ISSUE TITLE
Announce and kickoff for Frictionless Data Working Group

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#270]

**Comment by danfowler** [comment]
https://github.com/okfn/okfn.github.com/issues/469

**Comment by jobarratt** [comment]
@danfowler to write blog post to make the community aware that work is progressing and to draw attention to the specs.

**Comment by pwalsh** [comment]
blogpost moved to https://github.com/okfn/okfn.github.com/issues/469 and the original goals here met, so closing.
