### ISSUE TITLE
Announce Data Package Profile Registry

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#271]

**Comment by danfowler** [comment]
- [ ] Draw from: https://github.com/frictionlessdata/specs/issues/87#issuecomment-158302576
- [ ] Point to: http://schemas.frictionlessdata.io/registry.csv
- [ ] What is JSON Schema?
- [ ] Motivation
- [ ] How to Contribute
- [ ] Update registry URLs: https://github.com/frictionlessdata/schemas/issues/58

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/project/issues/332
