### ISSUE TITLE
Consolidate and fix bugs in specs

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#272]
- [x] https://github.com/frictionlessdata/specs/issues/275
- [x] https://github.com/frictionlessdata/specs/issues/274 (PR submitted)
- [ ] https://github.com/openspending/fiscal-data-package/issues/159
- [ ] https://github.com/okfn/specs/issues/7
- [ ] https://github.com/frictionlessdata/schemas/issues/44
- [ ] List features not covered in JSON Schemas: https://github.com/frictionlessdata/schemas/issues/59

**Comment by danfowler** [comment]
Closing as the rest of these issues are small and can be addressed at some point in the future.
