### ISSUE TITLE
Directly map out relation between JTS and W3C tabular data on the web

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#274]
Likely we can add a little plugin for our JTS libraries to support the important parts of the standard. It will also be useful to show people the differences, especially in terms of complexity.

**Comment by danfowler** [comment]
@Stephen-Gates you mentioned an area (types) where JTS and CSVW are not aligned.  Let's discuss that here!

https://discuss.okfn.org/t/how-do-you-describe-a-year-yyyy-in-a-json-table-schema/3524/3?u=danfowler

**Comment by Stephen-Gates** [comment]
@danfowler it was more that the JSON Table Schema "standards" being used to validate data by CSVLint and GoodTables seem to be different. E.g on http://csvlint.io/about the examples on how to give data a type (using constraints and references to http://www.w3.org/TR/xmlschema-2) are different to the [frictionlessdata specs](http://specs.frictionlessdata.io/json-table-schema/#field-types-and-formats)

**Comment by pwalsh** [comment]
I'm closing this for now. I really want to support `csvw` in the Table Schema libs, but, I'm not seeing much tooling or usage of CSV on the Web, and we are seeing pickup of JSON Table Schema in various places. When a clear use case arises, we'll deal with it on the code repositories in question.
