### ISSUE TITLE
Basic improvements to fd.io site

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#277]
- [x] Remove automatic expansion of menu on site load
- [x] Add mailing list link to front page
- [x] frictionlessdata/frictionlessdata.io: Issue https://github.com/frictionlessdata/frictionlessdata.io/issues/34

**Comment by danfowler** [comment]
Split off "Comparisons" section into new issue: https://github.com/frictionlessdata/frictionlessdata.io/issues/37

**Comment by danfowler** [comment]
Added basic link to newsletter: https://github.com/frictionlessdata/frictionlessdata.io/commit/e672f09dd95d56b2e64ba8c978ee04b884118c38

Next design should probably make newsletter more prominent.
