### ISSUE TITLE
Auto-toggled menu onload

### ISSUE THREAD

**Issue by todrobbins** [frictionlessdata/project#283]
As soon as I load http://frictionlessdata.io/ the menu slides out, pushing the homepage content to the side. Does this happening for anyone else? Is this meant to happen? If so, I don't understand the added value.

Cheers!

**Comment by danfowler** [comment]
No value.  Planning on removing 😄 .

**Comment by danfowler** [comment]
https://github.com/frictionlessdata/project/issues/277

**Comment by danfowler** [comment]
@todrobbins resolved 🔨
