### ISSUE TITLE
RFC: rows naming in tabular data representation

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#284]
# Overview

Tabular data is a key concept for the project. We describe tabular data with JSON Table Schema. Now we use different wording and default behaviors to read and write tabular data - it could be named as data, items, values, rows. It could be keyed or not keyed by default (see `jsontableschema.storage` and `datapackage.resource.iter`).

# Proposal

- to name **row - array of values** and emit it by default with all implementations thru the stack (`tabulator`, `jsontableschema` etc) 
- to name **keyed_row - dictionary of values** and emit it if `keyed=True` keyword is present (e.g. `table.iter(keyed=True)`
- to name **extended_row - array compliant to [number, headers, row]** and emit it if `extended=True` (for iteration protocol)

# Rationale

Naming should be consistent thru the stack. Don't use `keyed` by default because array of values is the most basic concept for tabular data and some datasets just can't be represented as keyed objects (non JTS, JTS with non-unique field names etc). So if a client knows that datasets could be represented with `keyed_rows` then he should use keyword argument to ask tool to make it keyed.

# Aside
It's not related to e.g. `goodtables` when adding keys could be part of pipeline etc. It's related to core tools reading data from files/storages/etc. 

# Updates
- 12.08 - added `extended_row` concept

---

@akariv 
@danfowler 
@pwalsh 
@vitorbaptista 
@zhenyab

**Comment by pwalsh** [comment]
@roll completely agreed.

**Comment by roll** [comment]
Thanks!
