### ISSUE TITLE
Archeology pilot transfer to forum

### ISSUE THREAD

**Issue by jobarratt** [frictionlessdata/project#286]
- [x] Working Group created: https://discuss.okfn.org/c/working-groups/open-archaeology
- [x] Create a forum post to be the focus for all activity on the Archeology Working group/Pilot: https://discuss.okfn.org/t/pilot-frictionless-data-in-archaeology/3440
- [x] Create a forum post for Hangout: https://discuss.okfn.org/t/hangout-frictionless-data-in-archaeology/3439
- [ ] Invite members of working group email list to forum

**Comment by danfowler** [comment]
@jobarratt added a checklist

**Comment by steko** [comment]
Thanks! I wouldn't link so prominently the spec proposal to the archaeology WG :smiley:

**Comment by danfowler** [comment]
@steko 👍

**Comment by danfowler** [comment]
@steko I've added two new blank posts for the forum: one for the hangout and one for the pilot.  We can fill them together if you like.  Once they are filled out, we can invite members of the email list to view and comment on these posts.
