### ISSUE TITLE
Open Power System Case study

### ISSUE THREAD

**Issue by jobarratt** [frictionlessdata/project#287]
Case Study for Open Power System

- [x] Transcribe interview
- [x] Edit interview for content
- [x] Have Open Power System Data review text
- [x] Prep PR
- [ ] Publish PR and merge only after 21 October

**Comment by jobarratt** [comment]
https://drive.google.com/open?id=15mt7iVQnTGCvCtSvJi9t6uTdr-7lvS0czjZEH50J5ls

**Comment by danfowler** [comment]
PR here: https://github.com/frictionlessdata/frictionlessdata.io/pull/97/files
