### ISSUE TITLE
RFC: Stack Reference [draft]

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#289]
# Stack Reference [draft]
## Architecture

![frictonless data 1](https://cloud.githubusercontent.com/assets/557395/17673886/d368f642-632b-11e6-9b59-3021952f09ca.png)
## Language
- row number - row number starting from 1
- col number - column number starting from 1
- headers - array of column names
- row - array of column values
- keyed row - dictionary of column values
- extended row - array containing row number, headers and row
- descriptor - dictionary describing something
### goodtables

```
Inspector(checks='all', 
          table_limit=10,
          row_limit=1000, 
          error_limit=1000,
          order_fields=False,
          infer_fields=False)
    inspect(source, preset='table', **options)
~@check(code, type, context, before/after)
~@preset(name)
exceptions
spec
~cli
```
### datapackage

```
Datapackage(descriptor, profile='base', base_path=None, remote_profiles=False, raise_invalid=True)
    valid -> dict
    errors -> list
    profile -> str
    descriptor -> dict
    resources -> Resource[]
    update(descriptor)
    addResource(descriptor)
    removeResource(index)
    save(target)
Resource(descriptor, profile='base', base_path=None)
    type -> local/remote/inline
    source -> path/data
    profile -> str
    descriptor -> dict
    table -> jsontableschema.Table/None
validate(descriptor, profile='base', remote_profiles=False) -> raise/True
exceptions
~cli
```
### jsontableschema

```
Table(source, schema=None, post_cast=None, backend=None, **options)
    stream -> tabulator.Stream
    schema -> Schema
    iter(keyed/extended=False) -> (generator) (keyed/extended)row[]
    read(keyed/extended=False, limit=None) -> (keyed/extended)row[]
    save(target, backend=None, **options)
Schema(descriptor)
    descriptor -> dict
    fields -> Field[]
    headers -> str[]
    primary_key -> str[]
    foreign_keys -> str[]
    get_field(name) -> Field
    has_field(name) -> bool
    cast_row(row) -> row
    save(target)
Field(descriptor)
    descriptor -> dict
    name -> str
    type -> str
    format -> str
    required -> bool
    constraints -> dict
    cast_value(value, skip_constraints=False) -> value
    test_value(value, skip_constraints=False, constraint=None) -> bool
infer(headers, values) -> descriptor
validate(descriptor) -> raise/True
exceptions
~cli
---
Storage(**options)
    buckets -> str[]
    create(bucket, descriptor, force=False)
    delete(bucket=None, ignore=False)
    describe(bucket, descriptor=None) -> descriptor
    iter(bucket) -> (generator) row[]
    read(bucket) -> row[]
    write(bucket, rows)
plugins
```
### tabulator

```
Stream(source, 
       headers=None,
       scheme=None, 
       format=None,  
       encoding=None, 
       sample_size=None,
       post_parse=None,
       **options)
    closed/open/close/reset
    headers -> list
    sample -> rows
    iter(keyed/extended=False) -> (generator) (keyed/extended)row[]
    read(keyed/extended=False, limit=None) -> (keyed/extended)row[]
    save(target, format=None, encoding=None, **options)
    ::test(source, scheme=None, format=None)
exceptions
~cli
```
## References
- [RFC: Rows naming in tabular data representation](https://github.com/frictionlessdata/project/issues/284)

**Comment by roll** [comment]
We could move this to docs to docs repo because it's not a task

**Comment by pwalsh** [comment]
@roll let's leave it and I'll get it into the site proper, or something, in the next weeks.

**Comment by roll** [comment]
@pwalsh 
Eventually I plan it to have as a part of documentation portal (like docs.frictionlessdata.io) with other documentation extracted from tools and libs. But for now I use it just as a live document.

**Comment by pwalsh** [comment]
@roll I think we should just have docs as part of a refactored frictionlessdata.io, rather than a distinct site, no? frictionlessdata.io is just basically rationale and guides anyway

**Comment by roll** [comment]
@pwalsh 
I think it's just an implementation question. For now now I see it as like autopulling all libs readme and docs into something like `mkdocs` setup. It will be easier to achive as a separate subproject. I suppose it's common practice to have separated dev/docs portal.

**Comment by roll** [comment]
could be closed in favor of https://github.com/frictionlessdata/stack/issues/2
