### ISSUE TITLE
Track and Upload Data Package data pilots

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#291]
We need to rigorously apply the Data Package concepts to real data and see where (a) it succeeds and provides real value and (b) where it falls short.  We need to do it in the open.  

Datasets to pilot:
- [ ] At least a subset of https://github.com/sje30/waverepo
- [ ] `example-retinal-mosaic` (also by @sje30)
- [ ] [The Cultural Evolution of Neolithic Europe. EUROEVOL Dataset 3: Archaeobotanical Data](http://openarchaeologydata.metajnl.com/articles/10.5334/joad.42/)

**Comment by pwalsh** [comment]
Closing as we have active pilots, and they are tracked in their own issue trackers. Here, there is no clear indication of what the action is, apart from the piloting that we do elsewhere.
