### ISSUE TITLE
Draft First Newsletter

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#308]
- [ ] International Data Week blog post
- [ ] Recent library updates
- [ ] Ruby libraries rolling

**Comment by pwalsh** [comment]
@jobarratt @danfowler did this happen? If not, do we need a dedicated ticket? maybe considering our size, we just do a newsletter send out on each FD-specific blogpost/announcement?

**Comment by danfowler** [comment]
@pwalsh I was imagining bundling a few announcements/blog posts in, say, a quarterly newsletter.
