### ISSUE TITLE
Example - Publish Data Package from Google Spreadsheet

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#31]
More of a blog post than something on the site (publish on e.g. okfnlabs.org). Think this is pretty useful.

Walk through of turning a google spreadsheet into a data package

- publish to the web
- get public CSV url for relevant sheet
- create datapackage.json (cf #28) and publish it somewhere
 - this is an important one - should we make this part of data.okfn.org itself (cf #52 - community catalog). Simplest option would be gist or even pasting the json into a google doc and getting raw text url for that (seems quite clunky!)

cf #30 (google spreadsheet export tool)

Cost: 2-3h

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#54
