### ISSUE TITLE
Open Referral HSDS Specification

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#316]
[Open Referral](https://openreferral.org/) has developed the [‘Human Service Data Specification’ (HSDS)](https://github.com/openreferral/specification).  It is a [Tabular Data Package](http://specs.frictionlessdata.io/tabular-data-package/).

> The ‘Human Service Data Specification’ (HSDS) is a data exchange format that enables resource directory data to be published once and used in many different ways. HSDS provides a common vocabulary for information about services, into which any given resource directory dataset can be translated and then exchanged with any other resource directory information system.

A [major push on the specs is happening](https://github.com/openreferral/specification/issues/99) with the [ODSC](http://opendataservices.coop/) (:tada:) and it would be good to stay in aligned!

Things we could do:
- Flag any issues where the HSDS diverges from the Tabular Data Package spec
  - e.g. "values" replaced by "enum" constraint, old "date" format, singular "license" key for array
- Create "hsds" profile by adding a [JSON Schema that validates it to the registry](https://github.com/frictionlessdata/schemas)
- Ensure [Tabular Data Package JSON Schema](https://github.com/frictionlessdata/schemas/blob/master/tabular-data-package.json) fully validates current Tabular Data Packages
- Schedule a guest post on our [Labs blog](http://okfnlabs.org/blog/) about current status

@frictionlessdata/specs-working-group

**Comment by danfowler** [comment]
The main output here will likely be one or more posts about how Open Referral uses the Frictionless Data specifications either on the Open Knowledge Labs or main blog, openreferral.org, or both.

And, of course, any recent updates to the specifications must be clearly communicated.

**Comment by danfowler** [comment]
Moving to the backlog until the next sprint.

**Comment by pwalsh** [comment]
@danfowler do you think there are any more action points on this?
