### ISSUE TITLE
Comms Plan

### ISSUE THREAD

**Issue by jobarratt** [frictionlessdata/project#318]
Work with Sierra to Create comms plan for the project

**Comment by jobarratt** [comment]
https://docs.google.com/document/d/1ouQGzr2iKpJS4B1z29tJ1pB-eJqjInV1_cwZhu3dhmw/edit#

**Comment by jobarratt** [comment]
This is done. Awaiting Sierra to review before we plan for the next stage.

**Comment by danfowler** [comment]
Great!
