### ISSUE TITLE
Example - House prices regressed on long interest rate and GDP (and population)

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#32]
* R example
* (Maybe we do in other languages too later ...)

*What does it demonstrate: quickly getting data and using it together*

## Required data

* [x] House price data - http://data.okfn.org/data/house-prices-uk
* [x] UK Long interest rate - http://data.okfn.org/data/bond-yields-uk-10y
* [x] UK GDP - http://data.okfn.org/data/gdp-uk

Do we need this quarterly?

## Why this analysis

* People are interested in house prices - why do they go up and down
* Classic explanation is other economic variables e.g. demand (GDP, population and interest rate (mortgages)), supply (housing stock). Here will just use demand variables and see what we find.

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#53
