### ISSUE TITLE
Blitz over all spec issues to prep for WG call

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#321]

**Comment by rgrp** [comment]
Note I would love to do a short sprint with you Paul on issues. I also have some uncommitted fixes for some issues ...

**Comment by pwalsh** [comment]
@rgrp yes, we have to. maybe we'll get time on Thursday. Let's see.

**Comment by roll** [comment]
@pwalsh 
my blitz - https://github.com/frictionlessdata/specs/labels/proposed-for-version-1

**Comment by rgrp** [comment]
@roll this was call that happened yesterday ;-)

**Comment by rgrp** [comment]
FIXED.
