### ISSUE TITLE
Investigate JTS for Bibliographic Records Validation

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#324]
- [x] Create topic on forum to centralize discussion among interested parties: https://discuss.okfn.org/t/validating-bibliographic-data/3881
- [x] Create Hubspot deal to track progress toward an action

**Comment by jobarratt** [comment]
Probably also perhaps a good idea to set these up in Hubspot.

**Comment by danfowler** [comment]
@jobarratt created deal and hubspot an forum post.
