### ISSUE TITLE
Create docs for pilots

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#326]

**Comment by pwalsh** [comment]
@danfowler ( cc @jobarratt ) can we not have issues that have no description of the work required. It is bad practice and hard for others to follow. I use this template:

```
# Description

<add narrative description of the issue here>

# Tasks

- [ ] <list clearly defined actions here>
```

You can use whatever you want, but don't create empty issues :).

**Comment by rufuspollock** [comment]
@jobarratt for people following the repo it is super useful to have some comment as to why the issue was fixed - is this wontfix / fixed / duplicate etc 😉

**Comment by danfowler** [comment]
Thanks @pwalsh will do in the future
