### ISSUE TITLE
Stats tool

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#33]
Given a Tabular Data Package compute stats for each file

A stat looks like:

<pre>
{
  count: record-count
  fields: [
    {
     name: field-id
     sum: 
     avg: 
     ... 
    }
  ]
}
</pre>

**Comment by rgrp** [comment]
@Stiivi - any thoughts or recommendations?

**Comment by rgrp** [comment]
@pwalsh i wonder if this relates to https://github.com/okfn/data-quality-cli also i'm wondering about a mini CSV/JSON "spec" for recording quality info based on our experience there and elsewhere (one for dataprotocols).

**Comment by pwalsh** [comment]
@rgrp agreed that the older work done in the above CLI and also in GoodTables reporter serves as a basic for, if not a quality/stats "spec", a pattern and a blueprint to iterate on an implementation thereof. I'd like to work on that, actually.

**Comment by danfowler** [comment]
Moved here: https://trello.com/c/oeBZW6vi/90-as-a-researcher-i-want-a-tool-that-can-generate-basic-statistics-about-a-dataset
