### ISSUE TITLE
Write a blog post about the latest features in the specs

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#335]
_From @rgrp on December 1, 2016 10:8_

- Data chunking
- Simplification of `path` and `url`
- Compressed resources
- ... 

_Copied from original issue: frictionlessdata/frictionlessdata.io#106_

**Comment by danfowler** [comment]
Hi @rgrp I move this from the other repo because we are not writing blog posts on frictionlessdata.io (and probably never will).  I imagine this will instead go on the Labs blog, but we should track its progress here.  I do think this is a good idea, especially for current users of the specs and to have a quick summary of recent changes.  I would also include a bit of motivation for each change.

Is it too early to write this, though?  For example, about "compressed resources", there's nothing to write here yet: https://github.com/frictionlessdata/specs/issues/290

@pwalsh @jobarratt WDYT?

**Comment by pwalsh** [comment]
Too early

**Comment by rgrp** [comment]
This was a holding item - i imagine this going out in january 😄

**Comment by pwalsh** [comment]
Closed in favour of https://github.com/frictionlessdata/project/issues/332
