### ISSUE TITLE
Tasks for PNNL Pilot

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#336]
- [x] Clone https://github.com/ActiveDataBio/ADB-User-Study into /frictionlessdata/ organization: https://github.com/frictionlessdata/ADB-User-Study
- [x] Add GitHub hook for goodtables.io (done by @amercader)
- [x] Add datapackage.json for /frictionlessdata/ADB-User-Study
- [x] Show Good Tables errors against `metadata.tsv`
- [x] Raise relevant issues against goodtables-py or goodtables.io 
- [x] Write up work to date

**Comment by jobarratt** [comment]
@danfowler can you add the relevant details here

**Comment by danfowler** [comment]
Added write-up to IDCC paper.

**Comment by roll** [comment]
@danfowler 
bases on tasks it's done?

**Comment by danfowler** [comment]
@roll Yes, thanks!
