### ISSUE TITLE
Fix anchor jump

### ISSUE THREAD

**Issue by julmot** [frictionlessdata/project#340]
In [this commit](https://github.com/diacritics/database/pull/13/commits/2a01ea2ce1eb483e778c296cb9d5023f0fdcae28#diff-e910483371fc42dbf4ebf8ec94d954e6R148) we're referencing the following URL:

http://data.okfn.org/data/core/language-codes#resource-ietf-language-tags

As you can see it contains an anchor that should normally jump directly to the specified section. Unfortunately, when opening this URL, it shows a different section.

**Comment by roll** [comment]
@julmot 
Thanks for the reporting! I've moved it to the repository owning the actual code of this problem - https://github.com/okfn/data.okfn.org-new/issues/30
