### ISSUE TITLE
bootstrap the essentials on the tool fund website

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#349]
in prep for sam to do design work.

Just a simple, single page website: toolfund.frictionlessdata.io

- Title
- 1 sentence what is the fund
- 1 paragraph on what is Frictionless Data
- 2 paragraphs on context of the fund
- Links/sections to:
  - Actual v1 specifications
  - Python and Javascript implementations
  - Implementation reference documentation
  - Link to submission form (submission form is a google form)

**Comment by jobarratt** [comment]
Made a start on this https://docs.google.com/document/d/17xNVI7lrsxiCcQXH0MtJtZsyYIfL9NHRR7ILRmzT7bg/edit

**Comment by pwalsh** [comment]
So this was actually done, and next step is design/implementation.
