### ISSUE TITLE
Tool Fund applications

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#354]
# Description

Periodically review Tool Fund applications.

**Comment by pwalsh** [comment]
# Process

One an applicant is successful and work can begin, the following steps need to occur.

## Repo setup

- tableschema-{LANG}
- datapackage-{LANG}

## Code distribution setup

- Create an OKI account for the code distribution service (e.g.: PyPi, npm, Packagist, Clojars)
- Document that the implementor needs to publish the libs to this service, and give the OKI account co-owner rights on the packages

## Issue flow

We've provided an implementation document, and have reference implementation in Python and JavaScript. This is a good start but we want to give implementors a bit more guidance on how to proceed:

- Bootstrap high-level tasks on the tableschema-{LANG} repo
- Bootstrap high-level tasks on the datapackage-{LANG} repo
- Implementors must do Table Schema first, as it is a hard dependency of Data Package implementations

## Communication

- All communication around the implementation must be in public. We want our work dynamic here to serve as an example for other implementors, and to share as much information as possible. There are two channels of communication:
  - GitHub Issues on tableschema-{LANG} and datapackage-{LANG}
  - Gitter chat at https://gitter.im/frictionlessdata/chat where all the core team at OKI are available for assistance
- The people who can help you are:
  - [Jo Barratt](https://github.com/jobarratt) - Project Manager for Frictionless Data
  - [Evgeny Karev](https://github.com/roll) - Tech Lead for core Frictionless Data libraries
  - [Serah Rono](https://github.com/callmealien) - Developer Advocate at Open Knowledge International, Dissemination Lead for the Tool Fund
  - [Dan Fowler](https://github.com/danfowler) - Developer Advocate at Open Knowledge International, Pilot Lead for Frictionless Data, OKI Labs Lead
  - [Adam Kariv](https://github.com/akariv) - Engineering Lead at Open Knowledge International, Tech Lead on OpenSpending
  - [Paul Walsh](https://github.com/pwalsh) - Chief Product Officer at Open Knowledge International
- Any communication around the grant agreement should be directly done by email with Jo Barratt, Frictionless Data Project Manager

**Comment by danfowler** [comment]
- Link to implementation guidance: http://specs.frictionlessdata.io/implementation/
- Suite of known valid Data Packages should be provided: https://github.com/frictionlessdata/testsuite-py/tree/master/datasets

**Comment by roll** [comment]
- Link to stack reference (recommended design/API): https://github.com/frictionlessdata/stack#frictionless-data-stack
