### ISSUE TITLE
How do you add a user story?

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/project#358]
I'd like to add a [user story](https://trello.com/b/MGC4RpTZ/frictionless-data-user-stories) that describes the [data card](http://preview.data.gov.au/data_cards/01.html) concept. 

As a communicator, I want to share data insights on social media, so that readers can easily verify and explore the data and related resources.

**Comment by serahrono** [comment]
This issue was moved to frictionlessdata/website#153
