### ISSUE TITLE
Develop Geo data specification protocol

### ISSUE THREAD

**Issue by henrykironde** [frictionlessdata/project#359]
From the previous discussion on issue https://github.com/frictionlessdata/specs/issues/86 
I have created a repository and I have included sample specifications that I have been working with. 

Note:
As s @Stephen-Gates stated in the previous discussion

```
I think a worked example using real data would help to clearly separate what's needed in a :

 **spatial data package**  - similar  [tabular-data-package](http://specs.frictionlessdata.io/tabular-data-package/) tabular data package E.g. 
 - Each resource MUST be a Spatial Data Resource 
 - or could a mix of Spatial and Tabular data be in a package? 
 - should spatial and temporal extent be described at this level or for each resource?
 
 **spatial data resource** - similar to  [tabular-data-resource](http://specs.frictionlessdata.io/tabular-data-resource/) tabular data resource 
 - the spatial reference system must be included 
 - the supported file types (GeoJSON, GML, etc)
 - would a CSV with point data be a valid resource?
**layer schema** - similar to [table schema](http://specs.frictionlessdata.io/table-schema)

```
There are two categories 

1.  Vector specifications
2.  Raster specification

- Each category should have it's own json file.
- Most of the vector data can be specified, including CSV geodata, GeoJSON, GML,
- A data package can describe several resources, if these resources share some common attributes, however to keep it simple we propose a one to one mapping of spatial file to json file.
(I think this will take care of issues relating to the level at which we describe certain properties )

For the case of raster files, the resources value is a list of bands with their identifying properties like group, variable, band name  etc.

For the case of vectors, the resources are the layers for that particular dataset

https://github.com/henrykironde/spatial-packages

**Comment by Stephen-Gates** [comment]
See also https://discuss.okfn.org/t/geo-data-package/6143

**Comment by serahrono** [comment]
This issue was moved to frictionlessdata/specs#545
