### ISSUE TITLE
Update Guides on the website

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/project#360]
At the moment the [guides](http://frictionlessdata.io/guides/) on the website are a bit of a mess. [Many tutorials](https://github.com/frictionlessdata/website/issues?q=is%3Aissue+is%3Aopen+label%3Atutorial
) have been identified as needing to be written. I'm wondering if there is a plan for this as I'd like to contribute.

**Comment by roll** [comment]
cc @vitorbaptista @serahrono
