### ISSUE TITLE
daff is awesome - let's (re)connect it with Frictionless Data

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#361]
@paulfitz 's daff work is awesome and we chatted with him lots when he started on this.

We should see if we can reconnect this actively with Frictionless stuff including getting http://dataprotocols.org/tabular-diff-format/ back up on main Frictionless Data specs

**Comment by rufuspollock** [comment]
@paulfitz ping :wink:

**Comment by paulfitz** [comment]
Hi @rufuspollock 😄 - you're talking about the page that was like this https://paulfitz.github.io/dataprotocols/tabular-diff-format/index.html right? Would it be helpful if I made a PR to https://github.com/frictionlessdata/specs to bring it back?

**Comment by rufuspollock** [comment]
Yes!

**Comment by rufuspollock** [comment]
@paulfitz any chance of you doing that PR? We can help 😄

**Comment by paulfitz** [comment]
Hmm, I have vague memories of trying, and scratching my head over the testing setup? This is all I can find lying around https://github.com/paulfitz/specs/commit/6f14d2f6a10ccebc72766bb6aa319f94aaff1001

**Comment by rufuspollock** [comment]
@paulfitz you don't need any of that json stuff - now it's just a simple README.md markdown file in a folder in the root of the repo 😄

**Comment by paulfitz** [comment]
Oh neat.  Working on a revival in https://github.com/paulfitz/specs/tree/add_back_daff_format.

Update: made PR at https://github.com/frictionlessdata/specs/pull/680

**Comment by rufuspollock** [comment]
FIXED. 😄 https://specs.frictionlessdata.io/tabular-diff/

👏 👏 @paulfitz
