### ISSUE TITLE
Improve dataprotocols.org redirect

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#362]
At the moment there is just a redirect in place for dataprotocols.org => frictionlessdata.io (not really correct anyway since should go to specs).

All other urls result in AWS bucket not found result which is a bit ugly.

## Tasks

* [ ] get dataprotocols.org onto cloudflare
* [ ] set up proper redirects (whole site urls to frictionlessdata.io/specs/

**Comment by lwinfree** [comment]
Closing in lieu of https://github.com/frictionlessdata/frictionlessdata.io/issues/872
