### ISSUE TITLE
Schema Catalog

### ISSUE THREAD

**Issue by johanricher** [frictionlessdata/project#368]
Hi,

After much discussions with @rufuspollock, we want to propose to create a catalog of Table Schemas hosted on frictionlessdata.io.

## Context

We're [Jailbreak](https://www.jailbreak.paris/), a French web development company focusing on data started by some former employees of Etalab (the national open data agency).

Since 2017, we've been working with @OpenDataFrance to create some Table Schemas in order to standardise common French open data datasets. This catalog of schemas is called [Socle commun des données locales](https://scdl.opendatafrance.net/) (SCDL) and now make use of the metadata properties we recently proposed as a [new spec pattern](https://github.com/frictionlessdata/specs/blob/master/specs/patterns.md#table-schema-metadata-properties).

A tool called [Validata](https://go.validata.fr/) was also developed based on Goodtables, to help French open data producers, such as local governments, follow the schemas.

To follow suit, @Etalab has then launched [schema.data.gouv.fr](https://schema.data.gouv.fr/), an official open data schema catalog, which is specific to France.

## Idea

So for the past 2 years we've increasingly been using Table Schemas and popularizing them in France. Modestly for now ([7 schemas](https://git.opendatafrance.net/scdl/catalog/)), but with Etalab starting its own website we think there's a chance it could catch on.

The idea is now to go next level and start a community-run schema catalog which would be inclusive and international, first to share Table Schemas but which could also be open other schemas such as Data Package Schemas or even others.

Each schema page could have link tools, calling users to actions for example "Validate a file" pointing to a validator such as Goodtables/Validata, "Create a file" pointing to a file editor such as [CSV Good Generator](https://github.com/etalab/csv-gg) developed by Etalab, etc.

The website for the catalog would have all the features needed such as full-text search and filtered search (by country, etc.).

It could also have an API to make use of the catalog within other projects, for example an open data portal proposing schemas when people upload a data package.

Those are some ideas that need to be expanded.

What do you think?

**Comment by rufuspollock** [comment]
DUPLICATE (MOVED) to https://github.com/frictionlessdata/forum/issues/5
