### ISSUE TITLE
Improve current issue  template

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#370]
Current form:

```
# Overview

Please replace this line with full information about your idea or problem. If it's a bug share as much as possible to reproduce it

---

Please preserve this line to notify @lwinfree (lead of this repository)
```

* @lwinfree you can just watch the repo - you don't need to be `@` in issues.
* the current overview does not tell us much and it starts with a heading which is unnecessary

**Comment by lwinfree** [comment]
Hey @rufuspollock , the person that is tagged isn't always me - it is the lead of that repo. The tagging is there to ensure that **someone** gets notified. Usually when it is tagging me, that is so I can then triage the issue to, say, Evgeny or you.

**Comment by rufuspollock** [comment]
@lwinfree right, though people who are "head of repo" can just watch that repo so they get notified.

**Comment by lwinfree** [comment]
@rufuspollock this way we can ensure that someone is definitely getting notified though, which is super helpful! Also, the person creating the issue now knows who they are talking to/can reach out to that person if they need more help. Seems like a win-win to me :-)

**Comment by rufuspollock** [comment]
FIXED / INVALID. I think this is now resolved / obsolete.
