### ISSUE TITLE
Creating a forum esp for "how do I" stuff as a github issue tracker

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#371]
We used to use the discuss.okfn.org, however i think something dedicated and with ability to resolve items is useful. Plus using a github tracker here would naturally align with where most of the rest of our work takes place.

I would therefore like to propose an "issues" only tracker name e.g. `forum` for this purpose and try it out for a month or two to see how it goes.

**Comment by rufuspollock** [comment]
@lwinfree i've just booted this for trial purposes here https://github.com/frictionlessdata/forum

LMK if you have any thoughts.

**Comment by lwinfree** [comment]
Sure let's give it a try! My initial thought is that it makes more sense for these issues to go to their corresponding github repository (eg questions about how do I use data package pipelines would go in that repo), but let's see how this goes.

**Comment by augusto-herrmann** [comment]
Actually, it has been bothering me for a few years how people tend not to use forums at all. The Open Knowledge forum is one of those, where hardly anyone but me posts anything in there. This move might put the nail in the coffin of the forums.

I think we have to try to discover the reason why people don't use the forum. If it is because they don't know the forum exists, perhaps we can fix it by putting links everywhere – the frictionless data website landing page, Github repositories, etc. However, if the reason people don't use forums is because they for some reason dislike them (I can't see why, as Discourse is awesome software), then moving the discussion elsewhere would be the way to go.

**Comment by rufuspollock** [comment]
> Actually, it has been bothering me for a few years how people tend not to use forums at all. The Open Knowledge forum is one of those, where hardly anyone but me posts anything in there. This move might put the nail in the coffin of the forums.

I don't think this will be a nail in the coffin of the OK forums (one way or the other). I think the issue with the OK forums (if there is one) is slightly different and not so much related to this e.g. they covered multiple topics, the engagement from country groups was slow to materialize (i can get into that etc but not here).

For me i really wanted something a bit more focused, interconnected with the repos themselves and with a clear open / closed aspect (i hope this "forum" to be more support like / "how do I" than discussion about ideas).

> I think we have to try to discover the reason why people don't use the forum. If it is because they don't know the forum exists, perhaps we can fix it by putting links everywhere – the frictionless data website landing page, Github repositories, etc. However, if the reason people don't use forums is because they for some reason dislike them (I can't see why, as Discourse is awesome software), then moving the discussion elsewhere would be the way to go.

That's a really good point. Right now i want to just start with a place where at least the core group of us start asking and answering stuff and then open that up as needed. *You* should be one of those so please do start opening issues 😄

**Comment by augusto-herrmann** [comment]
Now that you frame it like this, I actually think this is a great idea. :smile:

Normally I use the [Frictionless Data Gitter channel](https://gitter.im/frictionlessdata/chat) for that, but next time I have a question I'll remember to use it then.

**Comment by rufuspollock** [comment]
FIXED. We have this up and running and have a few items opened there. We can revisit and review this experiment in a few months.
