### ISSUE TITLE
[idea] Merging website issue tracker here (or at least restricting website to very technical stuff)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#372]
The FD website is a *major* part of FD and the issue tracker there contains a fair amount of generic items e.g. "Publishing data tutorials / patterns" - https://github.com/frictionlessdata/website/issues/51

It would make sense to have *one* clear focal issue tracker for general FD work.

Could we consolidate issue trackers - or, at the very least, restrict website issue tracker to very technical stuff.

**Comment by lwinfree** [comment]
Hi @rufuspollock Have you checked out the overall FD project board? https://github.com/orgs/frictionlessdata/projects/2 Is this kind of what you are envisioning?

**Comment by rufuspollock** [comment]
@lwinfree that's really useful - i had not seen that and kanban boards for tracking work overall is def useful.

My point though was a bit more e.g. i was also just wondering about reducing confusion about the places to post e.g. do *I* post a high level item about improving the website here or in the website issue tracker?

**Comment by lwinfree** [comment]
I like posting it in the website tracker. Most of the current issues are about improving the site, so i think it makes sense. Maybe we can update this: https://github.com/frictionlessdata/website/issues/184?

**Comment by rufuspollock** [comment]
@rufuspollock the point i had was that i'd kind of prefer one place - rather than this pm tracker *and* the website tracker. The website is a *massive* part of the general delivery of this project (i.e. not specific to a particular tool). So having two trackers one for PM and one for the website leads (at least for me) to wondering about where i should post (example is that issue you linked). At least for me i'm going to concentrate on this tracker for now.

**Comment by lwinfree** [comment]
@rufuspollock to me it seems like putting stuff here instead of on the website tracker is then making the issues be in 2 places? Which is what you are trying to not do? Am I not following?

**Comment by roll** [comment]
@lwinfree 
following our Slack conv. 

I've checked the website's issue and I would agree it seems mixed. 

I think the idea is to decide where is the main entry point for project issues. Limiting or closing some issue tracker feels a good move. Less is always better for me :smiley:  

E.g. checking project-level repos (project, website, fellow, etc)- https://github.com/frictionlessdata/software/blob/master/TEAMS.md#repositories

I would say that we can close almost all of the issues trackers there (I mean in the `project` subgroup) with a message that please use the `project` issue tracker (also adding the link to the site). In my opinion, `website` could be limited to presentation-only issues.

**Comment by lwinfree** [comment]
Ahhh OK thanks that makes more sense to me! I'm happy with that plan. @rufuspollock WDYT?

**Comment by rufuspollock** [comment]
@roll 👍 👍 and @lwinfree 

Let's do it. This can be a gradual thing where we first just add new issues here by default and then later actually do the issue merge as needed (I did a bulk move of issues recently and have tools for that if we need them).

**Comment by roll** [comment]
@lwinfree 
@rufuspollock 
I've been thinking and even I'd like to suggest something more radical.

Consider, we have a standard layout for the new site like https://vuepress.vuejs.org/. There one and only one `Github` link on the top.

I suggest:
- we merge all project-related trackers 
- we rename it to be `frictionlessdata/frictionlessdata.io` and put there the new site (optional but it feels more natural for Github to name the main entry point after your project name)
- we link this new united issue tracker from the new website header

**Comment by rufuspollock** [comment]
@roll 

* 👍 for one entry point place for new users to post issues and linking that from the website
* Not sure re merging all project related trackers - I'd want to think about that. Personally i think you may want to keep a few of these separate as these are code related and useful for the devs to have
* i would keep website repo and this issues repo separate

**Comment by rufuspollock** [comment]
FIXED. We are converging on this tracker as *the* tracker. See also https://github.com/frictionlessdata/project#where-to-open-issues
