### ISSUE TITLE
Have a proper about page explaining e.g. who is behind the project

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#374]
https://twitter.com/teh_aimee/status/1025545256668880897

> Who's behind the #frictionlessdata project? I've been on the site and can't find anything resembling an "about" section, explaining it, its provenance, how/why it came about, etc etc etc.

**Comment by rufuspollock** [comment]
We now have about *and* team page. Maybe we just want one page? Also about (or team) should give info about OKF and Datopian and perhaps a bit of the history of the project.

**Comment by lwinfree** [comment]
I think combining these pages would work - are you still interested in this idea @rufuspollock? I've got ideas for ways to improve both of these pages individually, so maybe we can discuss this during our next meeting?

**Comment by rufuspollock** [comment]
@lwinfree 👍 - both on combining and on ways we can improve.

**Comment by lwinfree** [comment]
done! https://frictionlessdata.io/people/
