### ISSUE TITLE
Tell people where to find Frictionless Data 

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/project#375]
[As discussed on the Forum](https://discuss.okfn.org/t/finding-data-packages/4207
) the Frictionless Data site does not help people find where frictionless data has been published.

We should make a view on the [Software](https://frictionlessdata.io/software/) page that points to repositories and platforms that support uploading and downloading frictionless data. 

You could argue that the platforms or universe views on the [Software](https://frictionlessdata.io/software/) page or even that the [Case Studies](https://frictionlessdata.io/articles/) do this but I'd like to see it a bit more explicit.

**Comment by augusto-herrmann** [comment]
> We should make a view on the Software page that points to repositories and platforms that support uploading and downloading frictionless data.

I'd rather have a dedicated "find frictionless data" page, or something like that, for listing the data platforms, instead of a section on the "software" page. I think we should put data as first class objects. People look for data first, and only then they look for tools for dealing with the data.

**Comment by rufuspollock** [comment]
@Stephen-Gates @augusto-herrmann we now have the work on the guide #430 and this would naturally fit in that - we could get this up very soon.

**Comment by lwinfree** [comment]
We've been discussing this some more in the community chat (in discord) and have decided to use #frictionlessdata in zenodo and github to tag frictionless data sets. @roll has also suggested displaying the github data as a list of links. Maybe it could go on the [adoption page](https://frictionlessdata.io/adoption/)?

**Comment by augusto-herrmann** [comment]
I think using the tag is a good idea, @lwinfree. However, the adoption page seems to be more about projects or groups/organizations. Maybe a subpage named "frictionless datasets" or "dataset examples", or something?

Anyway, I think there should be a way to catalog references to datasets just by URL as well, as not every dataset can be found on zenodo or github.

**Comment by roll** [comment]
We have something like this on our road map cc @lwinfree @alexkreidler

**Comment by lwinfree** [comment]
@roll this might be a nice project for Shashi!

**Comment by aivuk** [comment]
@roll we have this list at https://data-packages.frictionlessdata.io/ but as you said at the issue https://github.com/frictionlessdata/data-packages/issues/1 this is not optimal and maybe a better idea would be to think in a curated list, and users could suggest new datasets to it, maybe even using github issue as a request system, what do you think? This curated list can be added to the https://frictionlessdata.io/ website and a link to the framrwork website also.

**Comment by augusto-herrmann** [comment]
@aivuk maybe a good place for curated data packages lists would be [datahub.io](https://datahub.io/)?

**Comment by lwinfree** [comment]
@augusto-herrmann I'm pretty sure that datahub isn't being maintained right now.

**Comment by aivuk** [comment]
@roll @lwinfree Any thoughts about my question above?

**Comment by roll** [comment]
I think we can start from just having an article summing up the info similar to the initial comment in this thread. WDYT @lwinfree @aivuk

**Comment by lwinfree** [comment]
I like that the current site (https://data-packages.frictionlessdata.io/) uses Livemark, so I don't think that we need to create a new site/a new list. I think there are 3 things to change with the current site:
1) we should have a place where people can add their own datasets
2) the list of datasets is uncategorized/unorganized
3) the site isn't linked anywhere

For 1), we could create a google form where anyone can add their dataset (with the correct info). I think a google form will be easier than github issues. Then that data goes into a separate file [here](https://github.com/frictionlessdata/data-packages/tree/main/data) that then gets combined with the github api data (what do you think @roll?)?

For 2), I'm not sure what the best answer is. Maybe we can manually curate some of the data, but that seems like something that would take a long time & also immediately go out of date.

For 3), let's link to the datasets site on the main website, under Adoption. I'll open an issue to do this.

Also, @roll I'm not totally sure that you mean with "I think we can start from just having an article summing up the info similar to the initial comment in this thread." Do you mean we should write a blog about this?

**Comment by roll** [comment]
@lwinfree 
I mean that we can have an entry point on our website "Where to find Frictionless Datasets" which will be more high-level than a data package registry. This article might mention:
- data-package.frictionlessdata.io
- datahub.io
- zenodo datasets avaialble
- data.world data package export
- more and more
