### ISSUE TITLE
Announce the Website and Comms Improvement Initiative

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#377]
This can go on e.g. the FD blog

**Comment by cabral** [comment]
https://blog.okfn.org/2019/12/12/announcing-frictionless-data-joint-stewardship/

**Comment by rufuspollock** [comment]
@cabral where is the FIXED etc comment as per http://handbook.datopian.com/issues-tasks/#closing-issues

**Comment by rufuspollock** [comment]
FIXED. https://blog.okfn.org/2019/12/12/announcing-frictionless-data-joint-stewardship/
