### ISSUE TITLE
DataCatalog.js - Create your own data catalog in 5m from a list of your (or others) data packages

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#38]
* List of data packages
* datacatalog.js - see existing code Git and Github for Data - draft post
* host on s3 / file system / dropbox etc or similar ...

**Comment by rgrp** [comment]
Also could think about this on your local machine - a quick directory of your data packages.

**Comment by danfowler** [comment]
Moved here: https://trello.com/c/aMpM7pO3/91-datacatalog-js-create-your-own-data-catalog-in-5m-from-a-list-of-your-or-others-data-packages
