### ISSUE TITLE
High level roadmap

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#391]
When I am planning a website improvement project, I want to have an overview of the desired outcome and the major steps/milestones needed to reach it, so that I can create a high level strategy and follow it.

## Acceptance criteria

* [ ] A roadmap with key milestones (including end date)

## Tasks

* [ ] create a roadmap with key milestones

**Comment by rufuspollock** [comment]
@monikappv i don't get this - who is the "I" in "When I am planning". What's the connect of this with the issue tree etc. Can you clarify a bit.

**Comment by monikappv** [comment]
@rufuspollock in this case I guess you are...since you created the issue tree and came up with these subquestions. Should I type "When Rufus is ....", or? I don't understand.

This issue is a product of these branches in the issue tree (see below). However, looks like you changed the description from "A goal for alpha and production" to "A date by which this is complete"... So I just updated the issue based on these changes. 

![issuetree2](https://user-images.githubusercontent.com/56799741/70847745-8f71ed00-1e70-11ea-8f81-a625f601fd6e.png)

**Comment by rufuspollock** [comment]
@monikappv do you remember the comment about "not slavishly creating tasks / issues out of the issue tree" :wink:

**Comment by rufuspollock** [comment]
FIXED / INVALID. The high level roadmap *is* the issue tree https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1211596138

In addition i have filled the in the "high level roadmap" sub-item there with timings

* Research: end of Dec ✅
* Branding: first week of Jan ✅
* 20 Jan: skeleton site (maybe no theming) + repos updated
* 31 Jan: site ready
