### ISSUE TITLE
Experiment with Docusaurus2 for the new FD.io website

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#394]
@lwinfree
@rufuspollock
I've been working on the docs.frictionlessdata.io and ended up with prototyping the whole FD.io because the main site and the documentation site are really tied to each other (it's hard to find where the site ends and the documentation starts)

Here is my prototype:

# https://docs2.roll1.now.sh/

There are two aspects I wanted to share:

## CMS

I used Docusaurus2 static-site generator (https://v2.docusaurus.io/) because it's the leading solution for documentation portals and my initial goal was to update docs.frictionlessdata.io

I have found that:
- it has out-of-box a few really nice features i.e. search, projects showcase, blog, forum with an ability to vote; it fits really nicely with FD.io needs
- documentation reading experience is really great as advertised (much better than docsify)
- I've spent 1 day on the whole work = easy to use for basic cases

I think the CMS is similar to Gridsome but Docusaurus is backed by Facebook and uses React under the hood (though I don't think the difference between internals for such a small project/static-site is important).

## Informational Architecture

The second thing that was important for me is to play with the site structure. I've always had hard times understanding what the current FD.io try to do with me as a visitor; how it guides me through the information etc

I used the following principles:
- split information on sections by the audience (sections on top i.e. `Intro`, `Specs`, `Software` etc)
- within every section provide a book-like experience when you can just click the `Next Article` button and learn something new about the project starting from basics and ending with advanced materials
- finish every section with `What's Next?` article to guide a visitor to the next steps

---

I hope it's helpful. 

The source code is here - https://github.com/roll/docs2

**Comment by rufuspollock** [comment]
> I've been working on the docs.frictionlessdata.io and ended up with prototyping the whole FD.io because the main site and the documentation site are really tied to each other (it's hard to find where the site ends and the documentation starts)

😉 something i suspected would happen. this is very useful to see. Given that this sounds like this has now merged with the overall "redo the website(s)" work in https://github.com/frictionlessdata/project/projects/2 i suggest we merge in with that building on / reusing / learning from the work here.

**Comment by roll** [comment]
@Irio 
Here is also my other feedback

**Comment by rufuspollock** [comment]
FIXED. We did the experiment. Currently going with vuepress.
