### ISSUE TITLE
[v2] Map between Data Space and FD Products

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#404]
A structural map from mental model of data world (jobs to be done) to products (many-to-many with meaning in the links)

Child of #398, successor to #403

## Acceptance

* [x] Map from that to products

## Tasks

* [x]  Finish the the Data Integration Jobs+Pains taxonomy  and mapping https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930

**Comment by Irio** [comment]
FIXED. @monikappv and I mapped each of the listed job stories to the product under the Frictionless Data brand. They are list under the "Job Stories - High Level" sheet, columns "Our Offer (primary)," and "Our Offer (secondary)."

https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930
