### ISSUE TITLE
Excel Support for Publishing and Consuming Tabular Data Packages

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#41]
* Load a Tabular Data Package from a URL
* [Bonus] Search the primary Data Package registry (data.okfn.org/data) and then load the selected Data Package

We should look at Web Query Files: https://support.microsoft.com/en-us/kb/157482

**Comment by paulharris** [comment]
It would be good to be able to load a datapackage+CSV in Excel from local disk AND correctly set up Excel's formats (eg so it doesn't screw with the date format in the CSV).

**Comment by rgrp** [comment]
@paulharris +1 - that's exactly what is wanted. I guess this is macro style stuff (?) - i am not an excel user!

**Comment by paulharris** [comment]
I'm not sure, I don't use excel much either,
But I know users who like to, and it would be nice if excel wouldn't mess
with the date format.

We use the iso date + time format, and excel likes to change it to either :

Just the date (American style, which we don't use)
Or
Just the time (drop date and milliseconds)

Helpful!

**Comment by mattfullerton** [comment]
Should we just build a simple webservice that serves an Excel given a data package URL or posted data package as zip? i.e. ?url=mypackagelink.zip&output=xlsx

**Comment by rgrp** [comment]
@mattfullerton that's export and i think import (consumption) is probably no 1. Also one probably does want it built in if you can rather than having to go through external service but external service would be nice too!

**Comment by mattfullerton** [comment]
I know its nice to have it built in. I just figured export=import if the
service is easy. Can Excel open URLs?

Otherwise, the solution would probably be to write a plugin using Visual
Basic. We've done that here for CKAN->Webservice->MS Word and keep talking
about an Excel counterpart.

Matthew Fullerton
0176 5789 6501
Freiberuflicher Software Entwickler und EXIST Stipendiat beim
Gründungsvorhaben "Tapestry" - http://www.smartlane.de/

**Comment by paulharris** [comment]
It would need to be an off-line solution for me.
eg, XWiki had/has something you can install and it adds a button to MS Word.
Something like that.  Then I imagine you'd click "Load Package" button, and/or "Load CSV".

**Comment by paulharris** [comment]
I personally would need a disconnect solution, because the users would be
opening datasets downloaded to their PCs.
Once downloaded, further network access is not guaranteed or and thus not
reliable.

**Comment by Stephen-Gates** [comment]
Here's [something](https://docs.google.com/document/d/1bJSQeY_jhwIpEgA4L64v_OEGV4ae8miU6vX8u-wtHMk/edit?usp=sharing) I tried to encourage Microsoft Australia to progress - no luck but for what it's worth...

**Comment by paulharris** [comment]
Wouldn't Libreoffice be more open/extendible?

**Comment by akuckartz** [comment]
> Wouldn't Libreoffice be more open/extendible?

Sure.

**Comment by pwalsh** [comment]
LibreOffice would be more open/extendible, but a solution that works with Excel would be many, many times more useful IMHO (think: government office workflows and so on).

**Comment by mattfullerton** [comment]
I couldn't agree more. We first have to infect everyone with the joy of
open data before expecting them to see that they need to switch to open
software too ;-) And isn't xlsx sort of kind of open? I would envisage two
services: a live data package to xlsx converter service and a completely
internal Excel plugin.

Also I would expect someone who has made the leap to Libreoffice be more
able to first click a button on a webservice site to convert the package
and then open it manually. The same may not be true of all Excel users.

**Comment by rgrp** [comment]
@paulharris please open a separate issue for libreoffice support - that would be great :-)

**Comment by jamiekt** [comment]
Hi folks,
Just wanted to say that the extensibility model for Excel these days is no longer COM addins nor Visual Basic. VBA is still supported (I think) however Microsoft are now pushing the Office add-in spec (codename agaves). The nice thing about agaves is that the dev language is javascript, here's an example: https://msdn.microsoft.com/en-us/library/office/jj220065.aspx. Another nice thing is that (AFAIK) add-ins work across the Excel client, Excel Online, Excel on Mac, Excel on iOS & Excel on Android.

That is all.

**Comment by danfowler** [comment]
Hi @jamiekt thanks for the update!

**Comment by danfowler** [comment]
Moving this User Story to our new User Stories Trello Board: https://trello.com/c/4kTuIsGV/17-as-a-researcher-i-want-to-get-a-data-package-into-excel-in-seconds-so-that-i-can-start-using-the-data-for-doing-analysis-and-vis
