### ISSUE TITLE
Test Suites for Go

### ISSUE THREAD

**Issue by danielfireman** [frictionlessdata/project#457]
Hi @roll , I was looking at the [status page](https://github.com/frictionlessdata/software/blob/master/STATUS.md) and noticed that there are test suites for python, javascript, and ruby.

What is the work involved in getting go into it? Is there some documentation?

**Comment by rufuspollock** [comment]
@danielfireman should we keep this open or can we close this?

**Comment by danielfireman** [comment]
Hi @rufuspollock 

I believe we can close it. Unfortunately, I won't have the time to take this issue until I finish my Ph.D. :sob: (ETA end of year)
