### ISSUE TITLE
The improbability of being able to validate a date/time/datetime format if the source is excel

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#461]
# Overview

We need to test Excel date/time/datetime format on a few levels like `tabulator/tableschema/goodtables`. If improvements needed it probably should be on `tabulator` level.

---

_From @pwalsh_

When the source is Excel, we use xlrd's stuff to turn Excel's number formatting for dates into Python dates. At the time of converting the excel source into a text stream for use in goodtables, we don't know if there is a schema, or what the formatting of a date should be according to the schema. So, the date is forced to isoformat.

That means that later on, the only way that a date/time/datetime field from excel will pass its schema validation is if the `format` is set to any.

Just putting this here for future.

**Comment by rufuspollock** [comment]
@roll should we close this as wontfix / invalid or maybe move to the forum? Not really sure what this was about.

**Comment by roll** [comment]
I think it's fixed now
