### ISSUE TITLE
Consider alternative storage backends for large files on disk

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#462]
# Overview

Here is a proposal for alternative storages for extra large files.

---

_From @danfowler_

- [ ] HDF5 http://www.h5py.org/
- [ ] Feather https://github.com/wesm/feather
- [ ] Blaze http://blaze.readthedocs.io/en/latest/index.html

See: https://github.com/frictionlessdata/pilot-dm4t/issues/22#issuecomment-307781463
See: also see frictionlessdata/datapackage-pipelines#66

**Comment by rufuspollock** [comment]
WONTFIX / INVALID. I don't think we are planning much now (and going forward this kind of thing would go in the forum but not worth moving this one).
