### ISSUE TITLE
Swift Implementation Status

### ISSUE THREAD

**Issue by chrispomeroyhale** [frictionlessdata/project#465]
## Overview
I am writing an idiomatic Swift implementation of data package and table schema. I have a partial implementation of these libraries based on my own needs. A foundation is in place which provides a subset of features. There are still some architectural decisions to be revisited, additional tests to be written, and missing features to be implemented. I anticipate that this library will prove useful to someone and it could benefit from being more robust, too.

### Context
In addition to providing implementation status it may be helpful to place it in context. The Swift language is a product of the industry to support Apple's ecosystem including their evolving mobile platform. Their recent attitude shift allows for greater flexibility in transferring files. This is where my own usage comes into play: My emphasis is on enabling anyone to access their small data so that it can be carried with someone beyond the lifetime of an app.

Swift is a young language which comes with its strengths and needs. One of the challenges with Swift its lack of a stable ABI. In practice, this makes the library a moving target for developer-users but it doesn't prevent writing or consuming an open source library. Although this scenario is not unfamiliar for projects in languages like Python and JS, keys distinctions are the yearly pace at which Swift releases new language versions and the lack of the language in Linux distribution package managers.

Another consideration is Linux support. While Swift is functional on Linux, the foundational library is a community effort that is still a work in progress. By way of example, ISO 8601 date parsing support is incomplete. I view Linux as a secondary objective while this effort is ongoing.

### Notable Differences
Here are some derivations from the reference implementations. Any of these items may be reconsidered.

 * Descriptor deserialization results in a class representation of the descriptor over an object that maintains a JSON descriptor. Leverages failable initializers (i.e. factory methods that can return a null reference). As a consequence, serialization may not produce the same JSON.
 * Design choices revolving around the language being statically-typed over deferring type inference to the developer-user. Prefers types over ambiguity. Prefers maintaining an object graph over stringification where possible.
 * Use of log levels for errors (e.g. `MUST`, `REQUIRED`, `SHALL`) and warnings (e.g. `SHOULD`, `RECOMMENDED`). Provides a log over throwing exceptions which allows for a command-line utility to display all warnings and errors for a package.
 * No external dependencies.

### `datapackage`
Requirements not implemented or incomplete (strike-thru marks completion):

 * ~~read and validate a data package descriptor~~, including profile-specific validation via the registry of JSON Schemas
 * ~~create and edit a data package descriptor~~, including methods to add and remove resources and validation after editing
 * ~~provide an API to interact with a data package descriptor~~
 * streaming and reading of resources through a table schema with cast on iteration
 * ~~save a data package descriptor to a file path~~
 * save a data package as a zip file on disc
 * read a zip file containing a data package
 * _cover the latest changes in the specs such as string/array for `path` etc_
 * _support for schema dereferencing before validation_
 * _support for multipart resources_
 * ~~_support for csv dialects_~~

### `tableschema`
Requirements not implemented or incomplete (strike-thru marks completion):

 * ~~read and validate a table schema descriptor~~
 * ~~create and edit a table schema descriptor~~
 * ~~provide an API to interact with a table schema descriptor~~
 * infer a table schema descriptor from a supplied sample of data
 * validate a data source against the table schema descriptor, including in response to editing the descriptor
 * streaming and reading of a data source through a table schema with cast on iteration
 * ~~save a table schema descriptor to a file path~~
 * _cover the latest changes in the spec such as `bareNumber`, `true/falseValues`, `string PK/FK` etc_
 * _support true data streaming_
 * _support all data constraints_
 * _support all data types_

**Comment by rufuspollock** [comment]
@chrispomeroyhale how's this going? We'd love to publicize this /cc @lauragift21 @roll @lwinfree

**Comment by chrispomeroyhale** [comment]
@rufuspollock I am currently in the process of reviewing the DP/TDP implementation again and writing up documentation in preparation to publish. I am expecting to wrap that up in just a few days.

**Comment by rufuspollock** [comment]
@chrispomeroyhale great 👏 👏

**Comment by chrispomeroyhale** [comment]
@rufuspollock @roll I've now published the DP/TDP implementation. There's always something more to do, with CI and code coverage are next on my list. I should be available to chat on Discord now as well

**Comment by chrispomeroyhale** [comment]
@roll I'd like to set up TravisCI though I don't have permissions to enable/configure for these repos. I have a fork working with TravisCI and Codecov.io for code coverage integration. I see that other implementations are using Coveralls, but getting that working seems more involved as I don't know of a Coveralls tool that supports Swift projects using Swift Package Manager.

**Comment by roll** [comment]
Hi @chrispomeroyhale,

I have enabled Travis and Coveralls. Codecov seems not to need to be enabled but it requires a secret token (I can email or discord it to you if you'd like OR you can use your own)

BTW, maybe this project can help with Coveralls - https://github.com/macmade/xcode-coveralls? For other languages, we just run `coveralls` command from Travis and it works with no tokens

**Comment by roll** [comment]
Hi @chrispomeroyhale,

I've got your message in Discord. I think we don't need to set COVERALLS_TOKEN. It seems to be working without the token by checking that the coverage report is sent from Travis. We haven't added this token for any of our repos.

**Comment by chrispomeroyhale** [comment]
@roll I ended up getting Coveralls working a few weeks ago using `coveralls-lcov` since this project builds with Swift Package Manager and not Xcode (for minimal Linux support). Turns out neither Coveralls nor Codecov needed tokens on Travis CI.

Where we stand now: Both libraries are building on Travis CI with Coveralls code coverage integration and documentation on feature implementation status in the READMEs. The libraries are used in a shipping app in conjunction with my csv-dialect-swift project. Included is a simple CLI tool for displaying warnings/errors which could be used for library comparison absent validation against JSON Schema.

For the interested reader: I do have an unpublished [Core Data](https://en.wikipedia.org/wiki/Core_Data) "atomic store" for importing/exporting which I could potentially make available upon request -- not to be confused with OKFN's [Core Datasets](https://data.okfn.org/roadmap/core-datasets).

Although there's always more that can be done, for now these tools are serving my purpose. My hope is this may help pave the way towards opening up data accessibility options on Apple products.

**Comment by roll** [comment]
Awesome @chrispomeroyhale! 

@lwinfree @chrispomeroyhale, should we start introducing the Swift implementation to the community?

**Comment by lwinfree** [comment]
Yes I think we should share with the community now! I'll plan to write a post on discord tomorrow :-)

**Comment by chrispomeroyhale** [comment]
@lwinfree @roll Sure! I've just listed the packages on both [Swift Package Directory](https://www.swiftpackage.directory/) and [Swift Package Index](https://swiftpackageindex.com/) as well.

**Comment by roll** [comment]
That's differently DONE :tada: Thanks a lot @chrispomeroyhale
