### ISSUE TITLE
Design documentation infrastructure

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/project#466]
# Overview

Frictionless Data implementations is a middle-sized software project containing a lot of libraries of different languages. We need to design documentation infrastructure for it.

Current state - we use repository READMEs for all user-facing documentation.

# Tasks

- [ ] TBD

---

_From @vitorbaptista_

### How to write our technical reference? 

Currently, we write the technical reference (methods, arguments, return values, etc) in the README. Our docstrings just point to the relevant section. For example:

https://github.com/frictionlessdata/goodtables-py/blob/c1bc6995cffc2a3b92b8b351044074306012d5a2/goodtables/validate.py#L13-L15

I don't think this is the best approach, as we're breaking a well-established convention. This means that methods like `help()` won't work (which I use quite often in the REPL), IDEs won't be able to show you the docs, and we have to define the layouts ourselves (instead of using a tool like ReadTheDocs).

I like Twilio's strategy, which is to have just a small quickstart with 2-3 basic examples on the most important features, and use the readthedocs-style of tools that support each of the different languages. For example, this is their libraries' references page: https://www.twilio.com/docs/libraries/reference/, and this is the PHP library: https://github.com/twilio/twilio-php.

I think we should do something similar.

**Comment by rufuspollock** [comment]
INVALID (OBSOLETE). This discussion seems to now be obsolete though overall issue is still active and this content is valuable. I've captured content into a nascent rfc: https://github.com/frictionlessdata/project/blob/master/rfcs/0002-code-docs.md
