### ISSUE TITLE
[docs] Release notes

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/project#471]
- Add release notes to the docs
- Make sure release notes are comprehensive/show any breaking changes

**Comment by rufuspollock** [comment]
@roll @lauragift21 would it be ok to close this as it seems more of a "note to self" than an active issue (?)

**Comment by roll** [comment]
cc @lwinfree

**Comment by lwinfree** [comment]
I don't think this is done yet, but I can write more here to better explain:

We had users ask us for more complete release notes each time a release is done. They were dissatisfied with the current release notes they found, and especially asked for us to write down any major changes or any breaking changes in 1 place. (Note: I think these changes are sometimes hidden in issue comments).
@roll do you want to lead on this? I could help edit the notes before we release them if that would be helpful to you. Or maybe @lauragift21 would want to help with this too if she is interested (no pressure if you aren't interested!)

**Comment by roll** [comment]
@lwinfree 
All the core libraries follow SEMVER and have changelogs https://github.com/frictionlessdata/tableschema-py#changelog. Actually we haven't had any breaking changes for a few years already. Goodtables will have soon but it will be a new major version (v3) so it will be an established way to communicate such changes.

I think their main point was that `dataflows` is not v1 yet so the stability is unpredictable + I guess data package pipelines doesn't have a changelog.

**Comment by lwinfree** [comment]
OK thanks @roll. I think we can close this for now, with the plan being that we will make sure `dataflows` has better release notes when it is v1
