### ISSUE TITLE
[Use Case] Generate nice listing on web page from a table (with table schema)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#545]
Evidence for user need here https://github.com/per1234/inoliblist/issues/3#issuecomment-483460796 and https://github.com/per1234/inoliblist/issues/1

**Comment by lwinfree** [comment]
@roll is this similar to Livemark?

**Comment by roll** [comment]
@lwinfree 
It's this one - https://github.com/frictionlessdata/frictionless-py/issues/837 (partially) and partially Livemark

PS.
But yes it's closer to Livemark esp if we add column information to tables

**Comment by lwinfree** [comment]
I'm going to close this since I think it is out-of-scope for the project.

**Comment by roll** [comment]
Now it's fully implemented as Livemark's table - https://livemark.frictionlessdata.io/pages/feature-reference/markdown.html#table (with a schema can be provided)
