### ISSUE TITLE
tutorial on publishing geodata as a data package

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#90]
Basics are easy here.

Real question is whether there is a recommendation on data types. Main options afaict:

* geojson (+ topojson)
* shapefiles
* csv (with lon / lat columns or similar ...)
* spatialite / sqlite style

**Comment by rgrp** [comment]
@peterdesmet any more time?

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#52
