### ISSUE TITLE
[super] Publishing data tutorials / patterns

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#91]
* [x] general instructions - http://data.okfn.org/publish
* [x] tabular data #87 - http://data.okfn.org/doc/publish-tabular
* [ ] geo data #90 - http://data.okfn.org/doc/publish-geo
* [x] any kinds of data #123 - http://data.okfn.org/doc/publish-any

Common:

* [x] Putting your data packages online - http://data.okfn.org/doc/publish-online
* [ ] Creating DataPackage.json
* [ ] FAQs re standard conventions etc - #154

**Comment by rgrp** [comment]
Is this now a DUPLICATE of #182

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#51
